== JSON with Active Model Serializers

In previous chapter we added a `products` resource to the application and built all the necessary endpoints up to this point. We also associated the product model with the user and protected some of the `products_controller` actions on the way. By now you should feel really happy with all the work but we still have to do some heavy lifting. Currently we have something which look like this:

[source,json]
----
{
  "products": [
      {
          "id": 1,
          "title": "Tag Case",
          "price": "98.7761933800815",
          "published": false,
          "user_id": 1,
          "created_at": "2018-12-20T12:47:26.686Z",
          "updated_at": "2018-12-20T12:47:26.686Z"
      },
    ]
}
----

It doesn’t look nice, as the JSON output should render just an array of products, with the `products` as the root key. Something like this:

[source,json]
----
{
  "products": [
      {
          "id": 1,
          "title": "Tag Case",
      },
    ]
}
----

This is further explained in the http://jsonapi.org/format/#document-structure-resource-collection-representations[JSON API] website.

> A collection of any number of resources SHOULD be represented as an array of resource objects or IDs, or as a single "collection object"

I highly recommend you go and bookmark this reference. It is amazing and will cover some points I might not.

In this chapter we will customize the JSON output using the `active_model_serializers` gem, for more information you can review the https://github.com/rails-api/active_model_serializers[repository] on Github. I’ll cover some points in here from installation to implementation but I do recommend you check the gem docs on your free time.

You can clone the project up to this point with:

[source,bash]
----
$ git clone https://github.com/madeindjs/market_place_api.git -b chapter6
----

Let’s branch out this chapter with:

[source,bash]
----
$ git checkout -b chapter7
----

=== Setting up the gem

If you have been following the tutorial all along. you should already have the gem installed. But in case you just landed here I’ll walk you through the setup.

Add the following line to your `Gemfile`:

[source,ruby]
.Gemfile
----
# ...
gem 'active_model_serializers', '~> 0.10.8'
----

Run the `bundle install` command to install the gem and that is it. You should be all set to continue with the tutorial.

=== Serialise the user model

First we need to add a `user_serializer` file. We can do it manually but the gem already provides a command line interface to do so:

[source,bash]
----
$ rails generate serializer user
  create  app/serializers/user_serializer.rb
----

This created a file called `user_serializer` under the `app/serializers` directory, which should look like this:

[source,ruby]
.app/serializers/user_serializer.rb
----
class UserSerializer < ActiveModel::Serializer
  attributes :id
end
----

By now we should have some failing tests. Go ahead and try it:

[source,bash]
----
$ rspec spec/controllers/api/v1/users_controller_spec.rb
F.F....F.....
----

NOTE: In this case, Rails will look for a serializer named PostSerializer, and if it exists, use it to serialize the `Post`. This also works with `respond_with`, which uses `to_json` under the hood. Also note that any options passed to render `:json` will be passed to your serializer and available as `@options inside`. This means that no matter if we are using the `render json` method or `respond_with`, from now on Rails will look for the corresponding serializer first.

Now back to the specs. You can see that for some reason the response it’s not quite what we are expecting, and that is because the gem encapsulates the model into a javascript object with the model name as the root (in this case `user`).

So in order to make the tests pass we just need to add the attributes to serialize into the `user_serializer.rb` and update the `users_controller_spec.rb` file:

[source,ruby]
.app/serializers/user_serializer.rb
----
class UserSerializer < ActiveModel::Serializer
  attributes :id, :email, :created_at, :updated_at, :auth_token
end
----

Now if you run the tests now, they should be all green:

[source,bash]
----
$ rspec spec/controllers/api/v1/users_controller_spec.rb
.............

Finished in 0.16712 seconds (files took 0.80637 seconds to load)
13 examples, 0 failures
----

Let’s commit the changes:

[source,bash]
----
$ git add .
$ git commit -am "Adds user serializer for customizing the json output"
----

We can also test the serializer objects as shown on the https://github.com/rails-api/active_model_serializers#rspec[documentation] but I’ll let that to you to decide whether or not to test.

=== Serialize the product model

Now that we kind of understand how the serializers gem works it is time to customize the products output. The first step and as with the user we need a product serializer. So let’s do that:

[source,bash]
----
$ rails generate serializer product
    create  app/serializers/product_serializer.rb
----

Now let’s add the attributes to serialize for the product just as we did it with the user back in previous section:

[source,ruby]
.app/serializers/product_serializer.rb
----
class ProductSerializer < ActiveModel::Serializer
  attributes :id, :title, :price, :published
end
----

And that’s it. This is no more complicated as this. You can run all test suite but it will be green. Let’s commit the changes and move on onto next section.

[source,bash]
----
$ git add .
$ git commit -a "Adds product serializer for custom json output"
----

=== Serializing associations

We have been working with serializers and you may notice that it is quite simple. In some cases the hard decision is how to name your endpoints, or how to structure the JSON output, so your solution is kept through time.

When working with and API and associations between models there are many approaches you can take. Here I will explain what I found works for me and I let you judge. In this section we will extend our API to handle the product-user association. I’ll also explain some of the common mistakes or holes in which you can fall into.

Just to recap, we have a http://guides.rubyonrails.org/association_basics.html#the-has-many-association[has_many] type association between the user and product model. Check theses code snippets.

[source,ruby]
.app/models/user.rb
----
class User < ApplicationRecord
  has_many :products, dependent: :destroy
  # ...
end
----

[source,ruby]
.app/models/product.rb
----
class Product < ApplicationRecord
  belongs_to :user
  # ...
end
----

This is important because sometimes to save some requests from being placed it is a good idea to embed objects into other objects. This will make the output a bit heavier but when fetching many records this can save you from a huge bottleneck. Let me explain with a use case for the actual application as shown next.



.Use case of nested objects associations
****
Imagine a scenario where you are fetching the products from the API. In this scenario you need to display some of the user info.

One possible solution to this would be to add the `user_id` attribute to the `product_serializer` so we can fetch the corresponding user later. This might sound like a good idea but if you care about performance (or your database transactions are not fast enough) you should reconsider this approach. You have to realize that for every product you fetch you’ll have to request its corresponding user.

When facing this problem I’ve come with two possible alternatives:

* One good solution (in my opinion) is to embed the user ids related to the products into a meta attribute. So we have a JSON output like:

[source,json]
----
{
  "meta": { "user_ids": [1,2,3] },
  "products": [
  ]
}
----

This might need some further configuration on the user’s endpoint, so the client can fetch those users from those `user_ids`.

* Another solution (the one which I’ll be using here) is to embed the user object into de product object. This can make the first request a bit slower but this way the client does not need to make another extra request. An example of the expected output is presented below:

[source,json]
----
{
  "products":
  [
      {
         "id": 1,
         "title": "Digital Portable System",
         "price": "25.0277354166289",
         "published": false,
         "user": {
            "id": 2,
            "email": "stephany@lind.co.uk",
            "created_at": "2014-07-29T03:52:07.432Z",
            "updated_at": "2014-07-29T03:52:07.432Z",
            "auth_token": "Xbnzbf3YkquUrF_1bNkZ"
          }
      }
   ]
}
----
****

So we’ll be embedding the user object into the product. Let’s start by adding some tests. We will just modify the `show` and `index` endpoints spec.

[source,ruby]
.spec/controllers/api/v1/products_controller_spec.rb
----
# ...
RSpec.describe Api::V1::ProductsController, type: :controller do
  describe 'GET #show' do
    # ...
    it 'has the user as a embeded object' do
      expect(json_response[:user][:email]).to eql @product.user.email
    end
  end

  describe 'GET #index' do
    # ...
    it 'returns the user object into each product' do
      json_response.each do |product_response|
        expect(product_response[:user]).to be_present
      end
    end
  end
  # ...
end
----

The implementation is really easy. We just need to add one line to the product serializer:

[source,ruby]
.app/serializers/product_serializer.rb
----
class ProductSerializer < ActiveModel::Serializer
  attributes :id, :title, :price, :published
  has_one :user
end
----

Now if we run our tests, they should be all green:

[source,bash]
----
$ rspec spec
............................................................

Finished in 0.57068 seconds (files took 0.67788 seconds to load)
60 examples, 0 failures
----

==== Embedding products on users

By now you may be asking yourself if you should embed the products into the user the same as the the section above. Although it may sound fair, this can take to severe optimization problems, as you could be loading huge amounts of information and it is really easy to fall into the http://en.wikipedia.org/wiki/Circular_reference[Circular Reference problem] footnote:[in short loops the program until it runs out of memory and throws you and error or never respond you at all].

But don’t worry not all is lost. We can easily solve this problem, and this is by embedding just the `ids` from the products into the user, giving your API a better performance and avoid loading extra data. So in this section we will extend our products `index` endpoint to deal with a `product_ids` parameter and format the JSON output accordingly.

First we make sure the `product_ids` it is part of the user serialized object:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  describe 'GET #show' do
    # ...
    it 'has the product ids as an embeded object' do
      expect(json_response[:product_ids]).to eql []
    end
  end
  # ...
end
----

The implementation is very simple, as described by the `active_model_serializers` gem https://github.com/rails-api/active_model_serializers#embedding-associations[documentation]:

[source,ruby]
.app/serializers/user_serializer.rb
----
class UserSerializer < ActiveModel::Serializer
  attribute :product_ids do
    object.products.map(&:id)
  end
  # ...
end
----

We should have our tests passing:

[source,bash]
----
$ rspec spec/controllers/api/v1/users_controller_spec.rb
..............

Finished in 0.16791 seconds (files took 0.65902 seconds to load)
14 examples, 0 failures
----

Now we need to extend the `index` action from the `products_controller` so it can handle the product_ids parameter and display the scoped records. Let’s start by adding some specs:

[source,ruby]
.spec/controllers/api/v1/products_controller_spec.rb
----
# ...
RSpec.describe Api::V1::ProductsController, type: :controller do
  # ...
  describe 'GET #index' do
    before(:each) do
      4.times { FactoryBot.create :product }
      get :index
    end

    context 'when is not receiving any product_ids parameter' do
      before(:each) do
        get :index
      end

      it 'returns 4 records from the database' do
        expect(json_response).to have(4).items
      end

      it 'returns the user object into each product' do
        json_response.each do |product_response|
          expect(product_response[:user]).to be_present
        end
      end

      it { expect(response.response_code).to eq(200) }
    end

    context 'when product_ids parameter is sent' do
      before(:each) do
        @user = FactoryBot.create :user
        3.times { FactoryBot.create :product, user: @user }
        get :index, params: { product_ids: @user.product_ids }
      end

      it 'returns just the products that belong to the user' do
        json_response.each do |product_response|
          expect(product_response[:user][:email]).to eql @user.email
        end
      end
    end
  end
  # ...
end
----

As you can see from previous code we just wrapped the index action into two separate contexts: one which will receive the `product_ids`, and the old one we had which does not. Let’s add the necessary code to make the tests pass:

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  before_action :authenticate_with_token!, only: %i[create update destroy]

  def index
    products = params[:product_ids].present? ? Product.find(params[:product_ids]) : Product.all
    render json: products
  end
  # ...
end
----

As you can see the implementation is super simple. We simply just fetch the products from the `product_ids` params in case they are present, otherwise we just fetch all of them. Let’s make sure the tests are passing:

[source,bash]
----
$ rspec spec/controllers/api/v1/products_controller_spec.rb
..................

Finished in 0.35027 seconds (files took 0.65369 seconds to load)
18 examples, 0 failures
----

Let’s commit the changes:

[source,bash]
----
$ git commit -am "Embeds the products_ids into the user serialiser and fetches the correct products from the index action endpoint"
----

=== Searching products

In this last section we will keep up the heavy lifting on the `index` action for the products controller by implementing a super simple search mechanism to let any client filter the results. This section is optional as it’s not going to have impact on any of the modules in the app. If you want to practice more with TDD and keep the brain warm I recommend you complete this last step.

I’ve been using https://github.com/activerecord-hackery/ransack[Ransack] to build advance search forms extremely fast, but as this is an education tool (or at least I consider it), and the search we’ll be performing is really simple, I think we can build a simple search engine, we just need to consider the criteria by which we are going to filter the attributes. Hold tight to your seats this is going to be a rough ride.

We will filter the products by the following criteria:

* By a title pattern
* By price
* Sort by creation

This may sound short and easy but believe me it will give you a headache if you don’t plan it.

==== By keyword

We will create a scope to find the records which match a particular pattern of characters, let’s called it `filter_by_title`, let’s add some specs first:

[source,ruby]
.spec/models/product_spec.rb
----
# ...
RSpec.describe Product, type: :model do
  # ...
  describe '.filter_by_title' do
    before(:each) do
      @product1 = FactoryBot.create :product, title: 'A plasma TV'
      @product2 = FactoryBot.create :product, title: 'Fastest Laptop'
      @product3 = FactoryBot.create :product, title: 'CD player'
      @product4 = FactoryBot.create :product, title: 'LCD TV'
    end

    context "when a 'TV' title pattern is sent" do
      it 'returns the 2 products matching' do
        expect(Product.filter_by_title('TV')).to have(2).items
      end

      it 'returns the products matching' do
        expect(Product.filter_by_title('TV').sort).to match_array([@product1, @product4])
      end
    end
  end
end
----

The caveat in here is to make sure no matter the case of the title sent we have to sanitize it to any case in order to make the appropriate comparison in this case we’ll use the lower case approach. Let’s implement the necessary code:

[source,ruby]
.app/models/product.rb
----
class Product < ApplicationRecord
  # ...
  scope :filter_by_title, lambda { |keyword|
    where('lower(title) LIKE ?', "%#{keyword.downcase}%")
  }
end
----

The implementation above should be enough to make the tests pass:

[source,bash]
----
$ rspec spec/models/product_spec.rb
...........

Finished in 0.17178 seconds (files took 3.59 seconds to load)
11 examples, 0 failures
----

==== By price

In order to filter by price things can get a little bit tricky but actually it is very easy. We will break the logic to filter by price into two different methods: one which will fetch the products greater than the price received and the other one to look for the ones under that price. By doing this we keep everything really flexible and we can easily test the scopes.

Let’s start by building the `above_or_equal_to_price` scope specs:

[source,ruby]
.spec/models/product_spec.rb
----
# ...
RSpec.describe Product, type: :model do
  # ...
  describe '.above_or_equal_to_price' do
    before(:each) do
      @product1 = FactoryBot.create :product, price: 100
      @product2 = FactoryBot.create :product, price: 50
      @product3 = FactoryBot.create :product, price: 150
      @product4 = FactoryBot.create :product, price: 99
    end

    it 'returns the products which are above or equal to the price' do
      expect(Product.above_or_equal_to_price(100).sort).to match_array([@product1, @product3])
    end
  end
end
----

The implementation is extremely simple:

[source,ruby]
.app/models/product.rb
----
class Product < ApplicationRecord
  # ...
  scope :above_or_equal_to_price, lambda { |price|
    where('price >= ?', price)
  }
end
----

That should be sufficient. Let’s just verify everything is ok:

[source,bash]
----
$ rspec spec/models/product_spec.rb
............

Finished in 0.1566 seconds (files took 0.64782 seconds to load)
12 examples, 0 failures
----

You can now imagine how the opposite method will behave. Let’s add the specs:

[source,ruby]
.spec/models/product_spec.rb
----
# ...
RSpec.describe Product, type: :model do
  # ...
  describe '.below_or_equal_to_price' do
    before(:each) do
      @product1 = FactoryBot.create :product, price: 100
      @product2 = FactoryBot.create :product, price: 50
      @product3 = FactoryBot.create :product, price: 150
      @product4 = FactoryBot.create :product, price: 99
    end

    it 'returns the products which are above or equal to the price' do
      expect(Product.below_or_equal_to_price(99).sort).to match_array([@product2, @product4])
    end
  end
end
----

And now the implementation:

[source,ruby]
.app/models/product.rb
----
class Product < ApplicationRecord
  # ...
  scope :below_or_equal_to_price, lambda { |price|
    where('price <= ?', price)
  }
end
----

For our sake let’s run the tests and verify everything is nice and green:

[source,bash]
----
$ rspec spec/models/product_spec.rb
.............

Finished in 0.18008 seconds (files took 0.6544 seconds to load)
13 examples, 0 failures
----

As you can see we have not gotten in a lot of trouble. Let’s just add another scope to sort the records by date of last update. This is because in case the proprietary of the product decides to update some of the data, the client always fetches the most updated records.

==== Sort by creation

This scope is super easy, let’s add some specs first:

[source,ruby]
.spec/models/product_spec.rb
----
# ...
RSpec.describe Product, type: :model do
  # ...
  describe '.recent' do
    before(:each) do
      @product1 = FactoryBot.create :product, price: 100
      @product2 = FactoryBot.create :product, price: 50
      @product3 = FactoryBot.create :product, price: 150
      @product4 = FactoryBot.create :product, price: 99

      # we will touch some products to update them
      @product2.touch
      @product3.touch
    end

    it 'returns the most updated records' do
      expect(Product.recent).to match_array([@product3, @product2, @product4, @product1])
    end
  end
end
----

And now the code:

[source,ruby]
.app/models/product.rb
----
class Product < ApplicationRecord
  # ...
  scope :recent, lambda {
    order(:updated_at)
  }
end
----

All of our tests should be green:

[source,bash]
----
$ rspec spec/models/product_spec.rb
.............

Finished in 0.18008 seconds (files took 0.6544 seconds to load)
13 examples, 0 failures
----

Now it would be a good time to commit the changes as we are done adding scopes:

[source,bash]
----
$ git commit -am "Adds search scopes on the product model"
----

==== Search engine

Now that we have the ground base for the search engine we’ll be using in the app it is time to implement a simple but powerful search method, which will handle all the logic for fetching product records.

The method will consist on chaining all of the scopes we previously built and return the expected search. Let’s start by adding some tests:

[source,ruby]
.spec/models/product_spec.rb
----
# ...
RSpec.describe Product, type: :model do
  # ...
  describe '.search' do
    before(:each) do
      @product1 = FactoryBot.create :product, price: 100, title: 'Plasma tv'
      @product2 = FactoryBot.create :product, price: 50, title: 'Videogame console'
      @product3 = FactoryBot.create :product, price: 150, title: 'MP3'
      @product4 = FactoryBot.create :product, price: 99, title: 'Laptop'
    end

    context "when title 'videogame' and '100' a min price are set" do
      it 'returns an empty array' do
        search_hash = { keyword: 'videogame', min_price: 100 }
        expect(Product.search(search_hash)).to be_empty
      end
    end

    context "when title 'tv', '150' as max price, and '50' as min price are set" do
      it 'returns the product1' do
        search_hash = { keyword: 'tv', min_price: 50, max_price: 150 }
        expect(Product.search(search_hash)).to match_array([@product1])
      end
    end

    context 'when an empty hash is sent' do
      it 'returns all the products' do
        expect(Product.search({})).to match_array([@product1, @product2, @product3, @product4])
      end
    end

    context 'when product_ids is present' do
      it 'returns the product from the ids' do
        search_hash = { product_ids: [@product1.id, @product2.id] }
        expect(Product.search(search_hash)).to match_array([@product1, @product2])
      end
    end
  end
end
----

We added a bunch of code but the implementation is very easy (you’ll see). You can go further and add some more specs. In my case I did not find it necessary.

[source,ruby]
.app/models/product.rb
----
class Product < ApplicationRecord
  # ...
  def self.search(params = {})
    products = params[:product_ids].present? ? Product.find(params[:product_ids]) : Product.all

    products = products.filter_by_title(params[:keyword]) if params[:keyword]
    products = products.above_or_equal_to_price(params[:min_price].to_f) if params[:min_price]
    products = products.below_or_equal_to_price(params[:max_price].to_f) if params[:max_price]
    products = products.recent(params[:recent]) if params[:recent].present?

    products
  end
end
----

It is important to notice that we return the products as an https://api.rubyonrails.org/classes/ActiveRecord/Relation.html:[`ActiveRelation`] object so we can further chain more methods in case we need so (or paginate them which we will see on the last chapters). We just need to update the products controller index action to fetch the products from the `search` method:

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  before_action :authenticate_with_token!, only: %i[create update destroy]

  def index
    render json: Product.search(params)
  end
  # ...
end
----

We can run the whole test suite to make sure the app is healthy up to this point:

[source,bash]
----
$ rspec spec
.......................................................................

Finished in 1.49 seconds (files took 6.53 seconds to load)
71 examples, 0 failures
----

Let's commit theses changes:

[source,bash]
----
$ git commit -am "Adds search class method to filter products"
----

=== Conclusion

On chapters to come, we will start building the `Order` model, associate it with users and products, which so far and thanks to the https://github.com/rails-api/active_model_serializers[active_model_serializers] gem, it’s been easy.

This was a long chapter, you can sit back, rest and look how far we got. I hope you are enjoying what you got until now, it will get better. We still have a lot of topics to cover one of them is optimization and caching.
