[#chapter03-presenting-users]
= Présentation des utilisateurs


Dans le chapitre précédent, nous avons réussi à mettre en place les bases de la configuration de notre application.

Dans les prochains chapitres, nous traiterons l’authentification des utilisateurs à l’aide de jetons d’authentification ainsi que la définition de permissions pour limiter l’accès aux utilisateurs connectés. Nous relierons ensuite les produits aux utilisateurs et leur donnerons la possibilité de passer des commandes.

Vous pouvez cloner le projet jusqu’à ce point avec:

[source,bash]
----
$ git checkout tags/checkpoint_chapter03
----

Comme vous pouvez déjà l’imaginer, il existe de nombreuses solutions d’authentification pour Rails comme https://github.com/binarylogic/authlogic[AuthLogic], https://github.com/thoughtbot/clearance[Clearance] et https://github.com/plataformatec/devise[Devise]. Ces solutions sont des librairies clé en main, c'est à dire qu'elles permettent de gérer tout un tas de choses comme l'authentification, la fonctionnalité d'oubli de mot de passe, la validation, etc..

Nous ne les utiliserons pas afin de mieux appréhender le mécanisme d'authentification. Néanmoins nous allons utiliser la gemme https://github.com/codahale/bcrypt-ruby[bcrypt] afin de hasher le mots de passe de l'utilisateur.

Ce chapitre sera complet. Il sera peut-être long mais je vais essayer d’aborder autant de sujets que possible. N’hésitez pas à vous prendre un café et allons-y. A la fin de ce chapitre, vous aurez construit toute la logique des utilisateurs ainsi que la validation et la gestion des erreurs.

Nous voulons suivre ce chapitre, c’est donc un bon moment pour créer une nouvelle branche:

[source,bash]
----
$ git checkout -b chapter03
----

NOTE: Assurez-vous simplement d’être sur la branche `master` avant.

== Modèle d’utilisateur


=== Génération du modèle `User`

Nous allons commencer par générer notre modèle `User`. Ce modèle sera vraiment basique et contiendra seulement deux champs:

- `email` qui sera unique et lui permettra de se connecter à l'application
- `password_digest` qui contiendra la version *haché* du mot de passe (nous en reparlerons plus tard dans ce chapitre)

Afin de générer notre modèle `User`, nous utiliserons la méthode _generate model_ fournie par Ruby on Rails. Elle s'utilise très facilement:

[source,bash]
----
$ rails generate model User email:string password_digest:string
invoke  active_record
      create    db/migrate/20190603195146_create_users.rb
      create    app/models/user.rb
      invoke    test_unit
      create      test/models/user_test.rb
      create      test/fixtures/users.yml
----


NOTE: Dans le _design patern_ MVC, le modèle est l'élément qui contient les données ainsi que de la logique en rapport avec les données: validation, lecture et enregistrement. Nous allons donc dans un premier temps créer cette partie.

Cette commande génère beaucoup de fichiers! Ne vous inquiétez pas, nous allons les passer en revue les un après les autres.

Le fichier de migration contenu dans le dossier _db/migrate_ contient la *migration* qui décrit les modifications qui seront effectuées sur la base de données. Ce fichier devrait ressembler à ceci

.db/migrate/20190603195146_create_users.rb
[source,ruby]
----
class CreateUsers < ActiveRecord::Migration[6.0]
  def change
    create_table :users do |t|
      t.string :email
      t.string :password_digest

      t.timestamps
    end
  end
end
----


NOTE: la date insérée au début du nom du fichier de la migration devrait être différente chez vous puisque elle correspond à la date de création de la migration.

Nous allons modifier un petit peu cette migration afin d'ajouter quelques validations côté base de données. Avec Rails il est d'usage de faire ces verifications directement dans le modèle Ruby mais c'est une bonne pratique de le faire aussi dans le schéma de la base de données.

Nous allons donc rajouter deux contraintes:

- l'email est présent: on utilise la propriété `null: false`
- l'email est unique: on utilise la propriété `unique: true`
- le mot de passe est obligatoire: on utilise la propriété `null: false`

La migration devient donc:

.db/migrate/20190603195146_create_users.rb
[source,ruby]
----
# ...
create_table :users do |t|
  t.string :email, unique: true, null: false
  t.string :password_digest, null: false
  # ...
end
----

Une fois la migration terminée, nous pouvons effectuer les modifications avec la commande suivante:

.db/migrate/20190603195146_create_users.rb
[source,ruby]
----
$ rake db:migrate
== 20190603195146 CreateUsers: migrating ======================================
-- create_table(:users)
   -> 0.0027s
== 20190603195146 CreateUsers: migrated (0.0028s) =============================
----

NOTE: La commande va convertir notre migration en requête SQL qui va mettre à jour la base de données SQlite3 contenue dans le dossier _db_.

==== Le modèle

Nous avons donc défini notre schéma de la base de données. La prochaine étape est de mettre à jour notre modèle afin de définir les *règles de validation*. Ces règles se définissent dans le modèle situé dans le dossier _app/models_.

Ruby on Rails propose un mécanisme complet de validation que vous pouvez consulter sur https://guides.rubyonrails.org/active_record_validations.html[leur documentation officielle]. Dans notre cas, nous voulons valider deux choses:

- le courriel doit avoir un format valide
- le courriel doit être unique
- le mot de passe doit être rempli

Ces trois règles se définissent par le code suivant:

.app/models/user.rb
[source,ruby]
----
class User < ApplicationRecord
  validates :email, uniqueness: true
  validates_format_of :email, with: /@/
  validates :password_digest, presence: true
end
----

Et voilà. Rails utilise une syntaxe très simple et le code est très lisible.

.Validation du courriel
****
Vous remarquerez peut être que la validation du courriel utilise une validation simpliste en ne vérifiant que la présence d'un `@`.

C'est normal.

Une infinité d'exceptions existent en la matière d'adresse mail si bien https://davidcel.is/posts/stop-validating-email-addresses-with-regex/[que même `"Look at all these spaces!"@example.com` est une adresse valide]. Il vaut mieux donc privilégier une approche simple et confirmer le mail par un mail de validation.
****

==== Les tests unitaires

Nous terminons par les tests unitaires. Nous utilisons ici le framework de test Minitest qui est fourni par défaut avec Rails.

Minitest s'appuie sur des _Fixtures_ qui permettent de remplir votre base de données avec des données *prédéfinies*. Les _Fixtures_ sont définies dans des fichiers YAML dans le dossier `tests/fixtures`. Il y a un fichier par modèle.

Nous devons donc commencer par mettre à jour nos `tests/fixtures`.

NOTE: Les _fixtures_ ne sont pas conçues pour créer tous les données dont vos tests ont besoin. Elle permettent juste de définir les données basiques dont votre application a besoin.

Nous allons donc commencer par créer une _fixture_ définissant un utilisateur:

.test/fixtures/users.yml
[source,yaml]
----
one:
  email: one@one.org
  password_digest: hashed_password
----

Nous pouvons donc maintenant créer les tests. Il y en aura trois:

- nous vérifions qu'un utilisateur avec des données valides est valide:

.test/models/user_test.rb
[source,ruby]
----
# ...
test 'user with a valid email should be valid' do
  user = User.new(email: 'test@test.org', password_digest: 'test')
  assert user.valid?
end
----

- nous vérifions qu'un utilisateur avec un courriel invalide n'est pas valide:

.test/models/user_test.rb
[source,ruby]
----
# ...
test 'user with unvalid email should be unvalid' do
  user = User.new(email: 'test', password_digest: 'test')
  assert_not user.valid?
end
----

- nous vérifions qu'un utilisateur avec un courriel déjà utilisé n'est pas valide. Nous utilisons donc le même courriel que la _fixture_ que nous venons de créer.

.test/models/user_test.rb
[source,ruby]
----
# ...
test 'user with taken email should be unvalid' do
  other_user = users(:one)
  user = User.new(email: other_user.email, password_digest: 'test')
  assert_not user.valid?
end
----

Et voilà. Nous pouvons vérifier que notre implémentation est correcte juste en lançant simplement les tests unitaires que nous venons de créer:

[source,bash]
----
$ rake test
...
3 runs, 3 assertions, 0 failures, 0 errors, 0 skips
----

Je pense qu'il est temps de faire un petit _commit_ afin de valider notre avancement:

[source,bash]
----
$ git add . && git commit -m "Create user model"
----

=== Hachage du mot de passe

Nous avons précédemment mis en place le stockage des données de l'utilisateur. Il nous reste un problème à régler: *le stockage des mot de passe est en clair*.

> Si vous stockez les mots de passe des utilisateurs en clair, alors un attaquant qui vole une copie de votre base de données a une liste géante d'emails et de mots de passe. Certains de vos utilisateurs n'auront qu'un seul mot de passe -- pour leur compte de courriel, pour leur compte bancaire, pour votre application. Un simple piratage pourrait dégénérer en un vol d'identité massif. - https://github.com/codahale/bcrypt-ruby#why-you-should-use-bcrypt[source - Why you should use bcrypt]

Nous allons donc utiliser la gemme bcrypt afin de hacher le mot de passe.

NOTE: Le hachage consiste à transformer une chaîne de caractère en _Hash_. Ce _Hash_ ne permet pas de retrouver la chaîne de caractère d'origine. Cependant nous pouvons facilement l'utiliser afin de savoir si une chaîne de caractère donnée correspond au _hash_ que nous avons stocké.

Nous devons d’abord ajouter la gemme Bcrypt au _Gemfile_. Nous pouvons utiliser la commande `bundle add`. Celle-ci va s'occuper:

1. d'ajouter la gemme au Gemfile en récupérant la version actuelle
2. lancer la commande `bundle install` qui va installer la gemme et mettre à jour le fichier _Gemfile.lock_ qui "verrouille" la version actuelle de la gemme

Lancez donc la commande suivante:

[source,bash]
----
$ bundle add bcrypt
----

Une fois la commande exécutée, la ligne suivante est ajoutée à la fin du _Gemfile_:

[source,ruby]
.Gemfile
----
gem "bcrypt", "~> 3.1"
----

NOTE: La version 3.1 de bcrypt est celle actuelle à l'heure où j'écris ces lignes. Elle peut donc varier pour votre cas.


Active Record nous propose une méthode https://github.com/rails/rails/blob/6-0-stable/activemodel/lib/active_model/secure_password.rb#L61[`ActiveModel::SecurePassword::has_secure_password`] qui va s'interfacer avec Bcrypt et hacher le mot de passe pour nous très facilement.


[source,ruby]
.app/models/user.rb
----
class User < ApplicationRecord
  # ...
  has_secure_password
end
----

`has_secure_password` ajoute les validations suivantes:

* Le mot de passe doit être présent lors de la création.
* La longueur du mot de passe doit être inférieure ou égale à 72 octets.
* la confirmation du mot de passe à l'aide de l'attribut `password_confirmation` (s'il est envoyé)

De plus, cette méthode va ajouter un attribut `User#password` qui sera automatiquement haché et sauvegardé dans l'attribut `User#password_digest`.

Essayons cela tout de suite dans la console de Rails. Ouvrez une console avec `rails console`:

[source,ruby]
----
2.6.3 :001 > User.create! email: 'toto@toto.org', password: '123456'
 =>#<User id: 1, email: "toto@toto.org", password_digest: [FILTERED], created_at: "2019-06-04 10:51:44", updated_at: "2019-06-04 10:51:44">
----

Vous pouvez ainsi constater que lorsqu'on appelle la méthode `User#create!`, l'attribut `password` est haché et stocké dans `password_digest`. Nous pouvons aussi envoyer un attribut `password_confirmation` que ActiveRecord va comparer à `password`:

[source,ruby]
----
2.6.3 :002 > User.create! email: 'tata@tata.org', password: '123456', password_confirmation: 'azerty'
ActiveRecord::RecordInvalid (Validation failed: Password confirmation doesn t match Password)
----

Tout fonctionne comme prévus! Faisons maintenant un _commit_ afin de garder un historique concis:

[source,bash]
----
$ git commit -am "Setup Bcrypt"
----

== Construire les utilisateurs

Il est temps de faire notre premier point d’entrée. Nous allons juste commencer à construire l’action `show` pour l’utilisateur qui va afficher un utilisateur en JSON. Nous allons d’abord

1. générer le `users_controller`
2. ajouter les tests correspondants
3. construire le code réel.

Occupons nous tout d'abord de générer le contrôleur et les test fonctionnels.

Afin de respecter le visionnement de notre API, nous allons découper notre application en utilisant des *modules*. La syntaxe est donc la suivante:

[source,bash]
----
$ rails generate controller api::v1::users
----

Cette commande va créer le fichier `users_controller_test.rb`. Avant d’entrer dans le vif du sujet, il y a deux choses que nous voulons tester pour une API:

* La structure du JSON renvoyée par le serveur
* Le code de réponse HTTP renvoyé par le serveur

.Les codes HTTP courants
****
Le premier chiffre du code d’état spécifie l’une des cinq classes de réponse. Le strict minimum pour un client HTTP est qu’il utilise une ces cinq classes. Voici une liste des codes HTTP couramment utilisés:

* `200`: Réponse standard pour les requêtes HTTP réussies. C’est généralement sur les requêtes `GET`
* `201`: La demande a été satisfaite et a donné lieu à la création d’une nouvelle ressource. Après les demandes de `POST`
* `204`: Le serveur a traité la requête avec succès, mais ne renvoie aucun contenu. Il s’agit généralement d’une requête `DELETE` réussie.
* `400`: La requête ne peut pas être exécutée en raison d’une mauvaise syntaxe. Peut arriver pour tout type de requête.
* `401`: Similaire au 403, mais spécifiquement pour une utilisation lorsque l’authentification est requise et qu’elle a échoué ou n’a pas encore été fournie. Peut arriver pour tout type de requête.
* `404`: La ressource demandée n’a pas pu être trouvée mais peut être à nouveau disponible à l’avenir. Habituellement, concerne les requêtes `GET`
* `500`: Un message d’erreur générique, donné lorsqu’une condition inattendue a été rencontrée et qu’aucun autre message spécifique ne convient.

Pour une liste complète des codes de réponse HTTP, consultez l’ https://fr.wikipedia.org/wiki/Liste_des_codes_HTTP[article sur Wikipedia].
****

Nous allons donc implémenter le test fonctionnel qui vérifie l'accès à la méthode `Users#show`. pour cela,


[source,ruby]
.test/controllers/api/v1/users_controller_test.rb
----
# ...
class UsersControllerTest < ActionDispatch::IntegrationTest
  setup do
    @user = users(:one)
  end

  test "should show user" do
    get api_v1_user_url(@user), as: :json
    assert_response :success
    # on teste que la réponse contient le courriel
    json_response = JSON.parse(self.response.body)
    assert_equal @user.email, json_response['email']
  end
end
----


Il suffit ensuite d’ajouter l’action à notre contrôleur. C’est extrêmement simple:

[source,ruby]
.app/controllers/api/v1/users\_controller.rb
----
class  Api::V1::UsersController < ApplicationController
  def show
    render json: User.find(params[:id])
  end
end
----

Si vous exécutez les tests avec `rails test` vous obtenez l’erreur suivante:

[source,bash]
----
$ rails test

...E

Error:
UsersControllerTest#test_should_show_user:
DRb::DRbRemoteError: undefined method `api_v1_user_url' for #<UsersControllerTest:0x000055ce32f00bd0> (NoMethodError)
    test/controllers/users_controller_test.rb:9:in `block in <class:UsersControllerTest>'
----

Ce type d’erreur est très courant lorsque vous générez vos ressources à la main! En effet, nous avons totalement oublié *les routes*. Alors ajoutons-les:

[source,ruby]
.config/routes.rb
----
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [:show]
    end
  end
end
----

Vos tests devraient désormais passer:

----
$ rails test
....
4 runs, 5 assertions, 0 failures, 0 errors, 0 skips
----

Comme d’habitude, après avoir ajouté une des fonctionnalités dont nous sommes satisfaits, nous faisons un _commit_:

[source,bash]
----
$ git add . && git commit -m "Adds show action the users controller"
----

=== Tester notre ressource avec cURL

Nous avons donc enfin une ressource à tester. Nous avons plusieurs solutions pour la tester. La première qui me vient à l’esprit est l’utilisation de cURL qui est intégré dans presque toutes les distributions Linux. Alors, essayons:

[source,bash]
----
$ curl http://localhost:3000/api/v1/users/1
{"id":1,"email":"toto@toto.org", ...
----

Nous retrouvons bien l'utilisateur que nous avons crée avec la console Rails dans la section précédente. Vous avez maintenant une entrée d’API d’enregistrement d’utilisateur.

=== Créer les utilisateurs

Maintenant que nous avons une meilleure compréhension de la façon de construire des points d’entrée, il est temps d’étendre notre API. Une des fonctionnalités les plus importante est de laisser les utilisateurs créer un profil sur notre application. Comme d’habitude, nous allons écrire des tests avant d’implémenter notre code pour étendre notre suite de tests.

Assurez-vous que votre répertoire Git est propre et que vous n’avez pas de fichier en _staging_. Si c’est le cas, _committez_-les pour que nous puissions recommencer à zéro.

Commençons donc par écrire notre test en ajoutant une entrée pour créer un utilisateur sur le fichier `users_controller_test.rb` :

[source,ruby]
.test/controllers/users_controller_test.rb
----
# ...
class UsersControllerTest < ActionDispatch::IntegrationTest
  # ...
  test "should create user" do
    assert_difference('User.count') do
      post api_v1_users_url, params: { user: { email: 'test@test.org', password: '123456' } }, as: :json
    end
    assert_response :created
  end

  test "should not create user with taken email" do
    assert_no_difference('User.count') do
      post api_v1_users_url, params: { user: { email: @user.email, password: '123456' } }, as: :json
    end
    assert_response :unprocessable_entity
  end
end
----

Cela fait beaucoup de code. Ne vous inquiétez pas, je vous explique tout:

* dans le premier test nous vérifions la création d'un utilisateur en envoyant une requête POST valide. Ensuite, nous vérifiions qu'un utilisateur supplémentaire existe en base et que le code HTTP de la réponse est `created`
* dans le premier test nous vérifions que l'utilisateur n'est pas créé en utilisant un courriel déjà utilisé. Ensuite, nous vérifions que le code HTTP de la réponse est `created`

A ce moment là, les tests doivent échouer:

[source,bash]
----
$ rails test
...E
----

Il est donc temps d’implémenter le code pour que nos tests réussissent:

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  # ...

  # POST /users
  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user, status: :created
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

----

Rappelez-vous qu’à chaque fois que nous ajoutons une entrée dans notre API il faut aussi ajouter cette action dans notre fichier `routes.rb`.

[source,ruby]
.config/routes.rb
----
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: %i[show create]
    end
  end
end
----

Comme vous pouvez le constater, l’implémentation est assez simple. Nous avons également ajouté la méthode privée `user_params` pour protéger les assignations d’attributs en masse. Maintenant, nos tests devraient passer:

[source,bash]
----
$ rails test
......
6 runs, 9 assertions, 0 failures, 0 errors, 0 skips
----

Oura! _Committons_ les changements et continuons à construire notre application:

[source,bash]
----
$ git commit -am "Adds the user create endpoint"
----

=== Mettre à jour les utilisateurs

Le schéma de mise à jour des utilisateurs est très similaire à celui de la création. Si vous êtes un développeur de Rails expérimenté, vous connaissez peut-être déjà les différences entre ces deux actions:

* L’action de mise à jour répond à une requête PUT/PATCH .
* Seul un utilisateur connecté devrait être en mesure de mettre à jour ses informations. Ce qui signifie que nous devrons forcer un utilisateur à s’authentifier. Nous en parlerons au chapitre 5.

Comme d’habitude, nous commençons par écrire nos tests:

[source,ruby]
.test/controllers/users_controller_test.rb
----
# ...
class UsersControllerTest < ActionDispatch::IntegrationTest
  # ...
  test "should update user" do
    patch api_v1_user_url(@user), params: { user: { email: @user.email, password: '123456' } }, as: :json
    assert_response :success
  end

  test "should not update other user" do
    patch api_v1_user_url(@user), params: { user: { email: 'bad_email', password: '123456' } }, as: :json
    assert_response :unprocessable_entity
  end
end
----

Pour que les tests réussissent, nous devons construire l’action de mise à jour sur le fichier `users_controller.rb` et ajouter la route au fichier `routes.rb`. Comme vous pouvez le voir, nous avons trop de code dupliqué, nous remanierons nos tests au chapitre 4. Tout d’abord nous ajoutons l’action le fichier `routes.rb`:

[source,ruby]
.config/routes.rb
----
Rails.application.routes.draw do
  # ...
  resources :users, only: %i[show create update]
  # ...
end
----

Ensuite nous implémentons l’action de mise à jour sur le contrôleur utilisateur et faisons passer nos tests:

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: %i[show update]

  def show
    render json: @user
  end

  # ...

  def create
    @user = User.new(user_params)

    if @user.save
      render json: @user, status: :created
    else
      render json: @user.errors, status: :unprocessable_entity
    end
  end

  private
  # ...

  def set_user
    @user = User.find(params[:id])
  end
end

----

Tous nos tests devraient maintenant passer:

[source,bash]
----
$ rails test
........
8 runs, 11 assertions, 0 failures, 0 errors, 0 skips
----

Vue que tout fonctionne, on effectue un _commit_:

[source,bash]
----
$ git commit -am "Adds update action the users controller"
----

=== Supprimer l’utilisateur

Jusqu’à présent, nous avons construit pas mal d’actions sur le contrôleur des utilisateurs avec leurs tests mais ce n’est terminé. Il nous en manque juste une dernière qui est l’action de destruction. Créons donc le test:

[source,ruby]
.test/controllers/users_controller_test.rb
----
# ...
class UsersControllerTest < ActionDispatch::IntegrationTest
  # ...

  test "should destroy user" do
    assert_difference('User.count', -1) do
      delete api_v1_user_url(@user), as: :json
    end
    assert_response :no_content
  end
end
----

Comme vous pouvez le voir, le test est très simple. Nous ne répondons qu’avec un statut de *204* qui signifie `No Content`. Nous pourrions aussi retourner un code d’état de *200*, mais je trouve plus naturel de répondre `No Content` dans ce cas car nous supprimons une ressource et une réponse réussie peut suffire.

La mise en œuvre de l’action de destruction est également assez simple:

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]
  # ...

  def destroy
    @user.destroy
    head 204
  end

  # ...
end
----

N’oubliez pas d’ajouter l’action `destroy` dans le fichier `routes.rb`:

[source,ruby]
.config/routes.rb
----
Rails.application.routes.draw do
  # ...
  resources :users, only: %i[show create update destroy]
  # ...
end
----

Si tout est correct, vos tests devraient passer:

[source,bash]
----
$ rails test
.........
9 runs, 13 assertions, 0 failures, 0 errors, 0 skips
----

Rappelez-vous qu’après avoir apporté quelques modifications à notre code, il est de bonne pratique de les _commiter_ afin que nous gardions un historique bien découpé.

[source,bash]
----
$ git commit -am "Adds destroy action to the users controller"
----

Et comme nous arrivons à la fin de notre chapitre, il est temps d'appliquer toutes nos modifications sur la branche master en faisant un _merge_:

[source,bash]
----
$ git checkout master
$ git merge chapter03
----

== Conclusion

Oh vous êtes là! Bien joué! Je sais que c’était probablement long mais n’abandonnez pas! Assurez-vous que vous comprenez chaque morceau de code, les choses vont s’améliorer, dans le prochain chapitre, nous remanierons nos tests pour rendre le code plus lisible et plus maintenable. Alors restez avec moi!
