[#chapter09-optimization]
= Optimisations

Bienvenue dans le dernier chapitre du livre. Le chemin a été long mais vous n’êtes qu’à un pas de la fin. Dans le chapitre précédent, nous avons terminé la modélisation du modèle de commandes. Nous pourrions dire que le projet est maintenant terminé mais je veux couvrir quelques détails importants sur l’optimisation. Les sujets que je vais aborder ici seront:

* la pagination
* la mise en cache
* l'optimisation des requêtes SQL
* l'activation de CORS

J’essaierai d’aller aussi loin que possible en essayant de couvrir certains scénarios courants. J’espère que ces scenarii vous serons utiles pour certains de vos projets.

Si vous commencez à lire à ce stade, vous voudrez probablement que le code fonctionne, vous pouvez le cloner comme ça:

[source,bash]
----
$ git clone https://github.com/madeindjs/market_place_api.git -b chapter9
----

Créons une nouvelle branche pour ce chapitre:

[source,bash]
----
$ git checkout -b chapter09
----


== Pagination

Une stratégie très commune pour optimiser la récupération d’enregistrements dans une base de données est de charger seulement une quantité limitée en les paginant. Si vous êtes familiers avec cette technique, vous savez qu’avec Rails c’est vraiment très facile à mettre en place avec des gemmes telles que https://github.com/mislav/will_paginate[will_paginate] ou https://github.com/kaminari/kaminari[kaminari].

La seule partie délicate ici est de savoir comment gérer la sortie JSON pour donner assez d’informations au client sur la façon dont le tableau est paginé. Dans la section précédente, j’ai partagé quelques ressources sur les pratiques que j’allais suivre ici. L’une d’entre elles était http://jsonapi.org/ qui est une page incontournable des signets.

Si nous lisons la section sur le format, nous arriverons à une sous-section appelée https://jsonapi.org/format/#document-top-level[Top Level]. Pour vous expliquer rapidement, ils mentionnent quelque chose sur la pagination:

> "meta": méta-information sur une ressource, telle que la pagination.

Ce n’est pas très descriptif mais au moins nous avons un indice sur ce qu’il faut regarder ensuite au sujet de l’implémentation de la pagination. Ne vous inquiétez pas, c’est exactement ce que nous allons faire ici.

Commençons par la liste des produits.

=== Les produits

Nous allons commencer par paginer la liste des produits car nous n’avons aucune restriction d’accès. Cela nous facilitera les tests. Nous devons d’abord ajouter la gemme de kaminari à notre `Gemfile`:

[source,bash]
----
$ bundle add kaminari
----

Maintenant nous pouvons aller à l’action `Products#index` et ajouter les méthodes de pagination comme indiqué dans la documentation:

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  # ...
  def index
    @products = Product.page(params[:page])
                       .per(params[:per_page])
                       .search(params)

    render json: ProductSerializer.new(@products).serializable_hash
  end
  # ...
end
----

Jusqu’à présent, la seule chose qui a changé est la requête sur la base de données pour limiter le résultat à 25 par page (ce qui est la valeur par défaut). Mais nous n’avons toujours pas ajouté d’informations supplémentaires à la sortie JSON.

Nous devons fournir les informations de pagination sur la balise meta dans le formulaire suivant:

[source,json]
----
{
  "data": [
    ...
  ],
  "links": {
    "first": "/api/v1/products?page=1",
    "last": "/api/v1/products?page=30",
    "prev": "/api/v1/products",
    "next": "/api/v1/products?page=2"
  }
}
----

Maintenant que nous avons la structure finale de la balise meta, il ne nous reste plus qu’à la sortir sur la réponse JSON. Ajoutons d’abord quelques tests:

[source,ruby]
.test/controllers/api/v1/products_controller_test.rb
----
# ...
class Api::V1::ProductsControllerTest < ActionDispatch::IntegrationTest
  # ...
  test 'should show products' do
    get api_v1_products_url, as: :json
    assert_response :success

    json_response = JSON.parse(response.body, symbolize_names: true)
    assert_not_nil json_response.dig(:links, :first)
    assert_not_nil json_response.dig(:links, :last)
  end
  # ...
end
----

Le test que nous venons d’ajouter devrait échouer:

[source,bash]
----
$ rake test
......................F

Failure:
Api::V1::ProductsControllerTest#test_should_show_products [test/controllers/api/v1/products_controller_test.rb:13]:
Expected nil to not be nil.
----

Ajoutons les informations de pagination. Nous allons en faire une partie dans un _concern_ séparé afin de mieux découpler notre code:

[source,ruby]
.app/controllers/concerns/paginable.rb
----
# app/controllers/concerns/paginable.rb
module Paginable
  protected

  def current_page
    (params[:page] || 1).to_i
  end

  def per_page
    (params[:per_page] || 20).to_i
  end
end
----

Et maintenant nous pouvons l'utiliser dans le contrôleur.

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  include Paginable
  # ...

  def index
    @products = Product.page(current_page)
                       .per(per_page)
                       .search(params)

    options = {
      links: {
        first: api_v1_products_path(page: 1),
        last: api_v1_products_path(page: @products.total_pages),
        prev: api_v1_products_path(page: @products.prev_page),
        next: api_v1_products_path(page: @products.next_page),
      }
    }

    render json: ProductSerializer.new(@products, options).serializable_hash
  end
end
----


Maintenant, si on vérifie les spécifications, elles devraient toutes passer:

[source,bash]
----
$ rake test
..........................................
42 runs, 65 assertions, 0 failures, 0 errors, 0 skips
----

Maintenant que nous avons fait une superbe optimisation pour la route de la liste des produits, c’est au client de récupérer la `page` avec le bon paramètre `per_page` pour les enregistrements.

_Commitons_ ces changements et continuons avec la liste des commandes.

[source,bash]
----
$ git add .
$ git commit -m "Adds pagination for the products index action to optimize response"
----

// CURRENT

=== Liste des commandes

Maintenant, il est temps de faire exactement la même chose pour la route de la liste des commandes. Cela devrait être très facile à mettre en œuvre. Mais d’abord, ajoutons quelques tests au fichier `orders_controller_spec.rb`:

[source,ruby]
.spec/controllers/api/v1/orders_controller_spec.rb
----
# ...
RSpec.describe Api::V1::OrdersController, type: :controller do
  describe 'GET #index' do
    before(:each) do
      current_user = FactoryBot.create :user
      api_authorization_header current_user.auth_token
      4.times { FactoryBot.create :order, user: current_user }
      get :index, params: { user_id: current_user.id }
    end

    it 'returns 4 order records from the user' do
      expect(json_response[:data]).to have(4).items
    end

    it 'Have a meta pagination tag' do
      expect(json_response).to have_key(:meta)
      expect(json_response[:meta]).to have_key(:pagination)
      expect(json_response[:meta][:pagination]).to have_key(:'per-page')
      expect(json_response[:meta][:pagination]).to have_key(:'total-pages')
      expect(json_response[:meta][:pagination]).to have_key(:'total-objects')
    end

    it { expect(response.response_code).to eq(200) }
  end
  # ...
end
----

Et, comme vous vous en doutez peut-être déjà, nos tests ne passent plus:

[source,bash]
----
$ rspec spec/controllers/api/v1/orders_controller_spec.rb
.F........

Failures:

  1) Api::V1::OrdersController GET #index Have a meta pagination tag
     Failure/Error: expect(json_response).to have_key(:meta)
       expected #has_key?(:meta) to return true, got false
     # ./spec/controllers/api/v1/orders_controller_spec.rb:18:in `block (3 levels) in <top (required)>'

Finished in 0.66262 seconds (files took 2.74 seconds to load)
10 examples, 1 failure
----

Transformons le rouge en vert:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  before_action :authenticate_with_token!

  def index
    orders = current_user.orders.page(params[:page]).per(params[:per_page])
    render(
      json: orders,
      meta: {
        pagination: {
          per_page: params[:per_page],
          total_pages: orders.total_pages,
          total_objects: orders.total_count
        }
      }
    )
  end
  # ...
end
----

Les tests devraient maintenant passer:

[source,bash]
----
$ rspec spec/controllers/api/v1/orders_controller_spec.rb
..........

Finished in 0.35201 seconds (files took 0.9404 seconds to load)
10 examples, 0 failures
----

Faisons un _commit_ avant d’avancer

[source,bash]
----
$ git commit -am "Adds pagination for orders index action"
----

=== Factorisation de la pagination

Si vous avez suivi ce tutoriel ou si vous êtes un développeur Rails expérimenté, vous aimez probablement garder les choses DRY. Vous avez sûrement remarqué que le code que nous venons d’écrire est dupliqué. Je pense que c’est une bonne habitde de nettoyer un peu le code une fois la fonctionnalité implémentée.

Nous allons d’abord commencer par nettoyer ces tests qu’on a dupliqué dans le fichier `orders_controller_spec.rb` et `products_controller_spec.rb`:

[source,ruby]
----
it 'Have a meta pagination tag' do
  expect(json_response).to have_key(:meta)
  expect(json_response[:meta]).to have_key(:pagination)
  expect(json_response[:meta][:pagination]).to have_key(:'per-page')
  expect(json_response[:meta][:pagination]).to have_key(:'total-pages')
  expect(json_response[:meta][:pagination]).to have_key(:'total-objects')
end
----

Afin de le factoriser, nous allons créer un dossier `shared_examples` dans le dossier `spec/support/`.

[source,bash]
----
$ mkdir spec/support/shared_examples
----

Et maintenant, créons un fichier qui contiendra le code dupliqué

[source,ruby]
.spec/support/shared_examples/pagination.rb
----
shared_examples 'paginated list' do
  it 'Have a meta pagination tag' do
    expect(json_response).to have_key(:meta)
    expect(json_response[:meta]).to have_key(:pagination)
    expect(json_response[:meta][:pagination]).to have_key(:'per-page')
    expect(json_response[:meta][:pagination]).to have_key(:'total-pages')
    expect(json_response[:meta][:pagination]).to have_key(:'total-objects')
  end
end
----

Cet exemple partagé peut maintenant être utilisé pour remplacer les cinq tests des fichiers `orders_controller_spec.rb` et `products_controller_spec.rb`:

[source,ruby]
.spec/controllers/api/v1/orders_controller_spec.rb
----
# ...
RSpec.describe Api::V1::OrdersController, type: :controller do
  describe 'GET #index' do
    # ...
    it_behaves_like 'paginated list'
    # ...
  end
end
----

[source,ruby]
.spec/controllers/api/v1/products_controller_spec.rb
----
# ...
RSpec.describe Api::V1::ProductsController, type: :controller do
  # ...
  describe 'GET #index' do
    # ...
    it_behaves_like 'paginated list'
    # ...
  end
  # ...
end
----

Et les deux tests devraient passer.

[source,bash]
----
$ rspec spec/controllers/api/v1/
.................................................

Finished in 0.96778 seconds (files took 1.59 seconds to load)
49 examples, 0 failures
----

Maintenant que nous avons fait cette simple factorisation pour les tests, nous pouvons passer à l’implémentation de la pagination pour les contrôleurs et nettoyer les choses. Si vous vous souvenez de l’action d’indexation pour les deux contrôleurs de produits et de commandes, ils ont tous les deux le même format de pagination. Alors déplaçons cette logique dans une méthode appelée `pagination` sous le fichier `application_controller.rb`, de cette façon nous pouvons y accéder sur tout contrôleur qui aurait besoin de pagination.

[source,ruby]
.app/controllers/application_controller.rb
----
class ApplicationController < ActionController::API
  include Authenticable

  # @return [Hash]
  def pagination(paginated_array)
    {
      pagination: {
        per_page: params[:per_page],
        total_pages: paginated_array.total_pages,
        total_objects: paginated_array.total_count
      }
    }
  end
end
----

Il suffit ensuite d’utiliser cette méthode dans nos deux contrôlleurs:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  # ...
  def index
    orders = current_user.orders.page(params[:page]).per(params[:per_page])
    render(
      json: orders,
      meta: pagination(orders)
    )
  end
  # ...
end
----

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  # ...
  def index
    products = Product.search(params).page(params[:page]).per(params[:per_page])
    render(
      json: products,
      include: [:user],
      meta: pagination(products)
    )
  end
  # ...
end
----

Lançons les tests pour nous assurer que tout fonctionne:

[source,bash]
----
$ rspec spec/controllers/api/v1/
.................................................

Finished in 0.92996 seconds (files took 0.95615 seconds to load)
49 examples, 0 failures
----

Ce serait un bon moment pour _commiter_ les changements et passer à la prochaine section sur la mise en cache.

[source,bash]
----
$ git add .
----

== Mise en cache

Il y a actuellement une implémentation pour faire de la mise en cache avec la gemme `active_model_serializers` qui est vraiment facile à manipuler. Bien que dans les anciennes versions de la gemme, cette implémentation peut changer, elle fait le travail.

Si nous effectuons une demande à la liste des produits, nous remarquerons que le temps de réponse prend environ 174 milisecondes en utilisant cURL

[source,bash]
----
$ curl -w 'Total: %{time_total}\n' -o /dev/null -s http://api.marketplace.dev/products
Total: 0,174111
----

NOTE: L’option `-w` nous permet de récupérer le temps de la requête, `-o` redirige la réponse vers un fichier et `-s` masque l’affichage de cURL

En ajoutant seulement une ligne à la classe `ProductSerializer`, nous verrons une nette amélioration du temps de réponse!

[source,ruby]
.app/serializers/product_serializer.rb
----
class ProductSerializer < ActiveModel::Serializer
  # ...
  cache key: 'product', expires_in: 3.hours
end
----

[source,ruby]
.app/serializers/order_serializer.rb
----
class OrderSerializer < ActiveModel::Serializer
  # ...
  cache key: 'order', expires_in: 3.hours
end
----

[source,ruby]
.app/serializers/user_serializer.rb
----
class UserSerializer < ActiveModel::Serializer
  # ...
  cache key: 'user', expires_in: 3.hours
end
----

Et c’est tout! Vérifions l’amélioration:

[source,bash]
----
$ curl -w 'Total: %{time_total}\n' -o /dev/null -s http://api.marketplace.dev/products
Total: 0,021599
$ curl -w 'Total: %{time_total}\n' -o /dev/null -s http://api.marketplace.dev/products
Total: 0,021979
----

Nous sommes donc passés de 174 ms à 21 ms. L’amélioration est donc énorme! _Comittons_ une dernière fois nos changements.

[source,ruby]
----
$ git commit -am "Adds caching for the serializers"
----

== Conclusion

Si vous arrivez à ce point, cela signifie que vous en avez fini avec le livre. Bon travail! Vous venez de devenir un grand développeur API Rails, c’est sûr.

Merci d’avoir traversé cette grande aventure avec moi, j’espère que vous avez apprécié le voyage autant que moi. On devrait prendre une bière un de ces jours.
