[#chapter00-before]
= Avant-propos

"API on Rails 6" est basé sur http://apionrails.icalialabs.com/book/["APIs on Rails: Building REST APIs with Rails"]. Celui-ci fut initialement publié en 2014 par https://twitter.com/kurenn[Abraham Kuri] sous les licences http://opensource.org/licenses/MIT[MIT] et http://people.freebsd.org/~phk/[Beerware].

Cette première version, non maintenue, était prévue pour la version 4 de Ruby on Rails qui ne https://guides.rubyonrails.org/maintenance_policy.html#security-issues[reçoit plus que les mises à jour de sécurité]. J’ai voulu mettre à jour cet excellent ouvrage et contribuer à la communauté francophone en le traduisant moi-même et en l'adaptant aux nouvelles versions de Ruby on Rails. Ce livre est donc disponible pour la version 5.2 de Ruby on Rail et la version 6.0 (celle que vous lisez actuellement).

NOTE: Ce livre est aussi disponible dans la langue de Shakespeare.

Dans cette version je n'ai pas seulement cherché à rendre les exemples compatibles mais j'ai aussi voulu simplifier la mise en place d'une API avec Rails en utilisant des librairies plus récentes et surtout: maintenues.

== A propos de l’auteur original

Je m’appelle http://rousseau-alexandre.fr[Alexandre Rousseau] et je suis un développeur Rails passionné avec plus de 4 ans d’expérience (à l’heure où j’écris ces lignes). Je suis actuellement associé chez (https://isignif.fr[iSignif SAS]) où je construis et maintiens un produit de type SAAS en utilisant Rails. Je contribue aussi à la communauté Ruby en produisant et maintenant quelques gemmes que vous pouvez consulter sur https://rubygems.org/profiles/madeindjs[mon profil Rubygems.org]. La plupart de mes projets sont sur GitHub donc http://github.com/madeindjs/[n’hésitez pas à me suivre].

Tout le code source de ce livre est disponible au format https://asciidoctor.org[Asciidoctor] sur https://github.com/madeindjs/api_on_rails[GitHub]. Ainsi n’hésitez pas à https://github.com/madeindjs/api_on_rails/fork[forker] le projet si vous voulez l’améliorer ou corriger une faute qui m’aurait échappée.

== Droits d’auteur et licence

Cette traduction est disponible sous http://opensource.org/licenses/MIT[licence MIT]. Tout le code source de ce livre est disponible au format https://asciidoctor.org[Asciidoctor] sur https://github.com/madeindjs/api_on_rails[GitHub]

.licence MIT
****
La licence MIT Copyright (c) 2019 Alexandre Rousseau

La permission est accordée, à titre gratuit, à toute personne obtenant une copie de ce logiciel et la documentation associée, pour faire des modifications dans le logiciel sans restriction et sans limitation des droits d’utiliser, copier, modifier, fusionner, publier, distribuer, concéder sous licence, et / ou de vendre les copies du Logiciel, et à autoriser les personnes auxquelles le Logiciel est meublé de le faire, sous réserve des conditions suivantes:

L’avis de copyright ci-dessus et cette autorisation doivent être inclus dans toutes les copies ou parties substantielles du Logiciel.

LE LOGICIEL EST FOURNI «TEL QUEL», SANS GARANTIE D’AUCUNE SORTE, EXPLICITE OU IMPLICITE, Y COMPRIS, MAIS SANS S’Y LIMITER, LES GARANTIES DE QUALITÉ MARCHANDE, ADAPTATION À UN USAGE PARTICULIER ET D’ABSENCE DE CONTREFAÇON. EN AUCUN CAS LES AUTEURS OU TITULAIRES DOIVENT ÊTRE TENUS RESPONSABLE DE TOUT DOMMAGE, RÉCLAMATION OU AUTRES RESPONSABILITÉS, SOIT DANS UNE ACTION DE CONTRAT, UN TORT OU AUTRE, PROVENANT DE, DE OU EN RELATION AVEC LE LOGICIEL OU L’UTILISATION OU DE TRANSACTIONS AUTRES LE LOGICIEL.
****

"API on Rails 6" de https://github.com/madeindjs/api_on_rails[Alexandre Rousseau] est mis à disposition selon les termes de la licence http://creativecommons.org/licenses/by-sa/4.0/[Creative Commons Attribution - Partage dans les Mêmes Conditions 4.0 International]. Fondé sur une œuvre à http://apionrails.icalialabs.com/book/.

== Merci

Un grand merci à tous les contributeurs de Github qui rendent ce livre vivant. Par ordre alphabétique :

* https://github.com/airdry[airdry]
* https://github.com/Landris18[Landris18]
* https://github.com/lex111[lex111]
* https://github.com/cuilei5205189[cuilei5205189]
* https://github.com/franklinjosmell[franklinjosmell]
* https://github.com/notapatch[notapatch]
* https://github.com/tacataca[tacataca]
