[#chapter01-introduction]
= Introduction

Welcome to https://github.com/madeindjs/api_on_rails[APIs on Rails] a tutorial on steroids on how to build your next API with Rails. The goal of this book is to provide an answer on how to develop a RESTful API following the best practices out there, along with my own experience. By the time you are done with _API’s on Rails_ you should be able to build your own `API` and integrate it with any clients such as a web browser or your next mobile app. The code generated is built on top of Rails 4 which is the current version, for more information about this check out http://rubyonrails.org/. The most up-to-date version of the _API’s on Rails_ can be found on https://github.com/madeindjs/api_on_rails[APIs on Rails]; don’t forget to update your offline version if that is the case.

The intention with this book it’s not only to teach you how to build an API with Rails. The purpose is also to teach you how to build scalable and maintainable API with Rails which means improve your current Rails knowledge. In this journey we are going to take, you will learn to:

* Build JSON responses
* Use Git for version controlling
* Testing your endpoints
* Optimize and cache the API

I highly recommend you go step by step on this book, try not to skip chapters, as I mention tips and interesting facts for improving your skills on each on them. You can think yourself as the main character of a video game and with each chapter you’ll get a higher level.

In this first chapter I will walk you through on how to setup your environment in case you don’t have it already. We’ll then create the application called `market_place_api`. I’ll emphasize all my effort into teaching you all the best practices I’ve learned along the years, so this means right after initializing the project we will start tracking it with Git.

In the next chapters we will be building the application to demonstrate a simple workflow I use on my daily basis. We’ll develop the whole application using *test driven development* (TDD), getting started by explaining why you want to build an API’s for your next project and deciding whether to use JSON or XML as the response format. We’ll get our hands dirty then and complete the foundation for the application by building all the necessary endpoints, securing the API access and handling authentication through headers exchange. Finally on the last chapter we’ll add some optimization techniques for improving the server responses.

The final application will scratch the surface of being a market place where users will be able to place orders, upload products and more. There are plenty of options out there to set up an online store, such as http://shopify.com[Shopify], http://spreecommerce.com/[Spree] or http://magento.com[Magento].

By the end or during the process (it really depends on your expertise), you will get better and be able to better understand some of the bests Rails resources out there. I also took some of the practices from these guys and brought them to you:

* http://railscasts.com/[Railscasts]
* http://codeschool.com/[CodeSchool]
* http://jsonapi.org/format/[JSON API]

== Conventions on this book

The conventions on this book are based on the ones from http://www.railstutorial.org/book/beginning#sec-conventions[Ruby on Rails Tutorial]. In this section I’ll mention some that may not be so clear.

I’ll be using many examples using command-line commands. I won’t deal with windows `cmd` (sorry guys), so I’ll based all the examples using Unix-style command line prompt, as follows:

[source,bash]
----
$ echo "A command-line command"
A command-line command
----

I’ll be using some guidelines related to the language, what I mean by this is:

* *Avoid* means you are not supposed to do it
* *Prefer* indicates that from the 2 options, the first it’s a better fit
* *Use* means you are good to use the resource

If for any reason you encounter some errors when running a command, rather than trying to explain every possible outcome, I’ll will recommend you to `google it', which I don’t consider a bad practice or whatsoever. But if you feel like want to grab a beer or have troubles with the tutorial you can always mailto:contact@rousseau-alexandre.fr[email me].

== Development environments

One of the most painful parts for almost every developer is setting everything up, but as long as you get it done, the next steps should be a piece of cake and well rewarded. So I will guide you to keep you motivated.

=== Text editors and Terminal

There are many cases in which development environments may differ from computer to computer. That is not the case with text editors or IDE’s. I think for Rails development an IDE is way to much, but some other might find that the best way to go, so if that it’s your case I recommend you go with http://www.aptana.com/products/radrails[RadRails] or http://www.jetbrains.com/ruby/index.html[RubyMine], both are well supported and comes with many integrations out of the box.

* *Text editor*: I personally use http://www.vim.org/[vim] as my default editor with https://github.com/carlhuda/janus[janus] which will add and handle many of the plugins you are probably going to use. In case you are not a _vim_ fan like me, there are a lot of other solutions such as http://www.sublimetext.com/[Sublime Text] which is a cross-platform easy to learn and customize (this is probably your best option), it is highly inspired by http://macromates.com/[TextMate] (only available for Mac OS). A third option is to use a more recent text editor from the guys at http://gitub.com[GitHub] called https://atom.io/[Atom], it’s a promising text editor made with JavaScript, it is easy to extend and customize to meet your needs, give it a try. Any of the editors I present will do the job, so I’ll let you decide which one fits your eye.
* *Terminal*: If you decided to go with http://icalialabs.github.io/kaishi/[kaishi] for setting the environment you will notice that it sets the default shell to `zsh`, which I highly recommend. For the terminal, I’m not a fan of the _Terminal_ app that comes out of the box if you are on Mac OS, so check out http://www.iterm2.com/#/section/home[iTerm2], which is a terminal replacement for Mac OS. If you are on Linux you probable have a nice terminal already, but the default should work just fine.

=== Browsers

When it comes to browsers I would say http://www.mozilla.org/en-US/firefox/new/[Firefox] immediately, but some other developers may say https://www.google.com/intl/en/chrome/browser/[Chrome] or even https://www.apple.com/safari/[Safari]. Any of those will help you build the application you want, they come with nice inspector not just for the DOM but for network analysis and many other features you might know already.

=== Package manager

* *Mac OS*: There are many options to manage how you install packages on your Mac, such as https://www.macports.org/[Mac Ports] or http://brew.sh/[Homebrew], both are good options but I would choose the last one, I’ve encountered less troubles when installing software and managing it. To install `brew` just run the command below:

[source,bash]
----
$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
----

* *Linux*: You are all set!, it really does not matter if you are using `apt`, `pacman`, `yum` as long you feel comfortable with it and know how to install packages so you can keep moving forward.

=== Git

We will be using Git a lot, and you should use it too not just for the purpose of this tutorial but for every single project.

* on Mac OS: `$ brew install git`
* on Linux: `$ sudo apt-get install git`

=== Ruby

There are many ways in which you can install and manage ruby, and by now you should probably have some version installed if you are on Mac OS, to see which version you have, just type:

[source,bash]
----
$ ruby -v
----

Rails 6 requires you to install version 2.5 or higher. I recommend you to start using http://rvm.io/[Ruby Version Manager (RVM)] or http://rbenv.org/[rbenv], any of these will allow you to install multiple versions of `ruby`. We will use RVM in this tutorial any of these two options you choose is fine.

To install RVM go on https://rvm.io/ and get GPG keyfootnote:[The GPG allow you to verify author identity of the software you download.]. Then:

[source,bash]
----
$ gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
$ \curl -sSL https://get.rvm.io | bash
----

Next it is time to install ruby:

[source,bash]
----
$ rvm install 2.6
----

If everything went smooth, it is time to install the rest of the dependencies we will be using.

==== Gems, Rails & Missing libraries

First we update the gems on the whole system:

[source,bash]
----
$ gem update --system
----

On some cases if you are on a Mac OS, you will need to install some extra libraries:

[source,bash]
----
$ brew install libtool libxslt libksba openssl
----

We then install the necessary gems and ignore documentation for each gem:

[source,bash]
----
$ printf 'gem: --no-document' >> ~/.gemrc
$ gem install bundler
$ gem install foreman
$ gem install rails -v 6.0.0.rc1
----

NOTE: You may ask yoursel "what does RC1 mean?". RC1 means _Release Candidate_. As I write these lines, the final version for Rails 6.0 is not finished. So I use the he most recent version wich is 6.0.0.rc1

Check for everything to be running nice and smooth:

[source,bash]
----
$ rails -v
Rails 6.0.0.rc1
----

==== Database

I highly recommend you install http://www.postgresql.org/[Postgresql] to manage your databases, but for simplicity we’ll be using http://www.sqlite.org/[SQlite]. If you are using Mac OS you should be ready to go, in case you are on Linux, don’t worry we have you covered:

[source,bash]
----
$ sudo apt-get install libxslt-dev libxml2-dev libsqlite3-dev
----

or

[source,bash]
----
$ sudo yum install libxslt-devel libxml2-devel libsqlite3-devel
----

== Initializing the project

Initializing a Rails application must be pretty straightforward for you, if that is not the case, here is a super quick tutorial.

There is the command:

[source,bash]
----
$ mkdir ~/workspace
$ cd ~/workspace
$ rails new market_place_api --api
----

As you may guess, the commands above will generate the bare bones of your Rails application. The next step is to add some `gems` we’ll be using to build the api.

== Gemfile and Bundler

Once the Rails application is created, the next step is adding a simple but very powerful gem to serialize the resources we are going to expose on the api. The gem is called https://github.com/Netflix/fast_jsonapi[fast_jsonapi]. It's an excellent choice to building this kind of application and it is well maintained by https://www.netflix.com[Netflix].

You can add this gem simple using this command:

[source,bash]
.Gemfile
----
$ bundle add fast_jsonapi
----

So your `Gemfile` should look like this after adding the `fast_jsonapi` gem:

[source,ruby]
.Gemfile
----
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.3'

gem 'rails', '~> 6.0.0.rc1'
gem 'sqlite3', '~> 1.4'
gem 'puma', '~> 3.11'
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
gem "fast_jsonapi", "~> 1.5"
----

It is a good practice also to include the ruby version used on the whole project, this prevents dependencies to break if the code is shared among different developers, whether if is a private or public project.

It is also important that you update the `Gemfile` to group the different gems into the correct environment

[source,ruby]
.Gemfile
----
# ...
group :development do
  gem 'sqlite3'
end
# ...
----

This as you may recall will prevent `sqlite` from being installed or required when you deploy your application to a server provider like http://heroku.com/[Heroku].

After the command finish its execution, it is time to start tracking the project with Git.

== Versioning

Remember that Git helps you track and maintain history of your code. Keep in mind source code of the application is published on GitHub. You can follow the repository at https://github.com/madeindjs/api_on_rails[GitHub]. I’ll assume you have Git already configured and ready to use to start tracking the project. If that is not your case, follow these first-time setup steps:

[source,bash]
----
$ git config --global user.name "Type in your name"
$ git config --global user.email "Type in your email"
$ git config --global core.editor "vim"
----

NOTE: Replace the last command editor(`"mvim -f"`) with the one you installed `"subl -w"` for SublimeText ,`"mate -w"` for TextMate, or `"gvim -f"` for gVim.

Rails already initialize the new project as a brand new Git repository. If you encounter some problem you can initialize project like this:

[source,bash]
----
$ git init
----

Rails also provide a _.gitignore_ file to ignore some files that we don’t want to track. The default _.gitignore_ file should look like the one shown below:

..gitignore
----
# See https://help.github.com/articles/ignoring-files for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile '~/.gitignore_global'

# Ignore bundler config.
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3
/db/*.sqlite3-journal

# Ignore all logfiles and tempfiles.
/log/*
/tmp/*
!/log/.keep
!/tmp/.keep

# Ignore uploaded files in development.
/storage/*
!/storage/.keep
.byebug_history

# Ignore master key for decrypting credentials and more.
/config/master.key
----

After modifying the _.gitignore_ file we just need to add the files and commit the changes, the commands necessary are shown below:

[source,bash]
----
$ git add .
$ git commit -m "Initial commit"
----

TIP: I have encounter that committing with a message starting with a present tense verb, describes what the commit does and not what it did, this way when you are exploring the history of the project it is more natural to read and understand (or at least for me). I’ll follow this practice until the end of the tutorial.

Lastly and as an optional step we setup the GitHub (I’m not going through that in here) project and push our code to the remote server: We first add the remote:

[source,bash]
----
$ git remote add origin git@github.com:madeindjs/market_place_api.git
----

Then:

[source,bash]
----
$ git push -u origin master
----

As we move forward with the tutorial, I’ll be using the practices I follow on my daily basis, this includes working with `branches`, `rebasing`, `squash` and some more. For now you don’t have to worry if some of these don’t sound familiar to you, I walk you through them in time.

== Conclusion

It’s been a long way through this chapter, if you reach here let me congratulate you and be sure that from this point things will get better. So let’s get our hands dirty and start typing some code!
