[#chapter05-athentification]
= Autenticando al usuario

Ha sido un largo tiempo desde que iniciamos. Espero que te guste este viaje tanto como a mí.

En el capítulo anterior configuramos las entradas de recursos para los usuarios. Si te saltaste este capítulo o si no entendiste todo, te recomiendo encarecidamente que lo mires. Éste cubre las primeras bases de las pruebas y es una introducción a respuestas JSON.

Puedes clonar el proyecto hasta este punto:

[source,bash]
----
$ git checkout tags/checkpoint_chapter04
----

En este capítulo las cosas se pondrán muy interesantes porque vamos a configurar el mecanismo de autenticación. En mi opinión es uno de los capítulos más interesantes. Introduciremos un montón de términos nuevos y terminarás con un simple pero poderoso sistema de autenticación. No sientas pánico vamos por ello.

La primera cosa es que primero (y como es usual cuando iniciamos un nuevo capítulo) vamos a crear una nueva rama:

[source,bash]
----
$ git checkout -b chapter04
----

== Sesion sin estado

Antes de que hagamos algo, algo debe estar claro: *una API no maneja sesiones*. Si no tienes experiencia construyendo este tipo de aplicaciones puede sonar un poco loco pero quédate conmigo. Un API puede ser sin estado lo cual significa por definición _es una que provee una respuesta después de tú petición, y luego no requiere más atención_. Lo cual significa que un estado previo o un estado futuro no es requerido para que el sistema trabaje.

El flujo para autenticar al usuario mediante una API es muy simple:

. La petición del cliente para el recurso `sessions` con las correspondientes credenciales (usualmente email y password)
. El server regresa el recurso `user` junto con su correspondiente token de autenticación
. Para cada página que requiere autenticación el cliente tiene que enviar el `token de autenticación`

Por supuesto estos no son los únicos 3 pasos a seguir, y en el paso 2 debería pensar, bien yo realmente ¿necesito responder con la información del usuario o solo el `token de autenticación`? Yo podría decir que eso realmente depende de tí, pero a mí me gusta regresar el usuario completo, de esta forma puedo mapearlo de inmediato en mi cliente y guardar otra posible solicitud que haya sido echa.

En esta sección y la siguiente vamos a enfocarnos en construir un controlador de sesiones junto a sus acciones correspondientes. Vamos entonces a completar el flujo de solicitudes agregando los accesos de autorización necesarios.


=== Presentación de JWT

Cuando nos acercamos a los tokens de autenticación, tenemos un estándar: el JSON Web Token (JWT).

> JWT es un estándar abierto definido en RFC 75191. Este permite el intercambio seguro de tokens entre varias partes. - https://wikipedia.org/wiki/JSON_Web_Token_Web_Token[Wikipedia]

En general un token JWT se compone de tres partes:

- un *header* estructurado en JSON contiene por ejemplo la fecha de validación del token.
- un *payload* estructurado en JSON puede contener *cualquier dato*. En nuestro caso, contiene el indetificador del usuario "conectado".
- un *signature* que nos permite verificar que el token fue encriptado por nuestra aplicación y es por lo danto válido.

Estas tres partes son cada una codificadas en base64 y entonces concatenadas usando puntos (`.`). Lo cual nos da algo como:

.Un token JWT válido
----
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
----

Una ves decodificado, este token nos da la siguiente información:

.La cabecera del token JWT
[source,json]
----
{ "alg": "HS256", "typ": "JWT" }
----

.El payload de el token JWT
[source,json]
----
{ "sub": "1234567890", "name": "John Doe", "iat": 1516239022 }
----

NOTE: Para más información sobre tokens JWT te invito a visitar https://jwt.io[jwt.io]

Esto tiene muchas ventajas justo como enviar información en payload de tokens. Por ejemplo, podemos elegir integrar información del usuario en el _payload_.

=== Configurando el token de autenticación

El estándar JWT tiene muchas implementaciones en varios lenguajes y librerías. Por supuesto, hay una gema de Ruby en este tema: https://github.com/jwt/ruby-jwt[ruby-jwt].

Asi que vamos a comenzar instalándola:

[source,bash]
----
$ bundle add jwt
----

Una vez completada la siguiente línea es añadida a tu _Gemfile_:

[source,ruby]
----
gem "jwt", "~> 2.2"
----

La librería es muy simple. Hay dos métodos: `JWT.encode` y `JWT.decode`. Vamos a abrir una terminal con `console rails` y a correr algunas pruebas:

[source,ruby]
----
2.6.3 :001 > token = JWT.encode({message: 'Hello World'}, 'my_secret_key')
2.6.3 :002 > JWT.decode(token, 'my_secret_key')
 => [{"message"=>"Hello World"}, {"alg"=>"HS256"}]
----

En la primera línea codificamos un _payload_ con la llave secreta `my_secret_key`. así obtenemos un token que podemos decodificar de manera simple. La segunda línea decodifica el token y vemos que podemos encontrar sin dilema nuestro _payload_.

Vamos a incluir toda la lógica en una clase `JsonWebToken` en un nuevo archivo localizado en `lib/`. Esto nos permite evitar el código duplicado. Esta clase justamente codificará y decodificará los tokens JWT. Así que aquí está la implementación.

.lib/json_web_token.rb
[source,ruby]
----
class JsonWebToken
  SECRET_KEY = Rails.application.secrets.secret_key_base.to_s

  def self.encode(payload, exp = 24.hours.from_now)
    payload[:exp] = exp.to_i
    JWT.encode(payload, SECRET_KEY)
  end

  def self.decode(token)
    decoded = JWT.decode(token, SECRET_KEY).first
    HashWithIndifferentAccess.new decoded
  end
end
----

Yo se que es un montón de código pero lo revisaremos juntos.

- el método `JsonWebToken.encode` se encarga de codificar el _payload_ añadiendo una fecha de expiración de 24 horas por defecto. Además usamos la misma llave de encriptación que viene configurada con Rails.
- el método `JsonWebToken.decode` decodifica el token JWT y obtiene el _payload_. Entonces usamos la clase https://api.rubyonrails.org/classes/ActiveSupport/HashWithIndifferentAccess.html[`HashWithIndifferentAccess`] proveída por Rails la cual nos permite recuperar un valor de un `Hash` con un `Symbol` ó `String`.

Ahí tienes. Para cargar el archivo en tú aplicación, necesitas especificar el directorio `lib` en la lista de _autoload  de Ruby on rails. Para hacerlo, agrega la siguiente configuración al archivo `application.rb`:

.config/application.rb
[source,ruby]
----
# ...
module MarketPlaceApi
  class Application < Rails::Application
    # ...
    config.eager_load_paths << Rails.root.join('lib')
  end
end
----
Y eso es todo. Ahora es tiempo de hacer un commit:

[source,bash]
----
$ git add . && git commit -m "Setup JWT gem"
----


=== Controlador de Token

Tenemos sin embargo que configurar el sistema para generar un token JWT. Es ahora tiempo de crear una ruta que generará este token. Las acciones que implementaremos serán administradas como servicios _RESTful_: la conexión será gestionada por una petición POST a la acción `create`.

Para empezar, iniciaremos creando el controlador y el método `create` en el _namespace_ `/api/v1`. Con Rails, una orden es suficiente:


[source,bash]
----
$ rails generate controller api::v1::tokens create
----

Modificaremos la ruta un poco para respetar las convenciones _REST_:

.config/routes.rb
[source,ruby]
----
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # ...
      resources :tokens, only: [:create]
    end
  end
end
----


Vamos a construir pruebas funcionales antes de ir más lejos. El comportamiento deseado es el siguiente:

- Yo recibo un token si envío un email valido junto con el password
- de otro modo el server responde un `forbidden`

Las pruebas por lo tanto se materializan de la siguiente forma:

.test/controllers/api/v1/tokens_controller_test.rb
[source,ruby]
----
require 'test_helper'

class Api::V1::TokensControllerTest < ActionDispatch::IntegrationTest
  setup do
    @user = users(:one)
  end

  test 'should get JWT token' do
    post api_v1_tokens_url, params: { user: { email: @user.email, password: 'g00d_pa$$' } }, as: :json
    assert_response :success

    json_response = JSON.parse(response.body)
    assert_not_nil json_response['token']
  end

  test 'should not get JWT token' do
    post api_v1_tokens_url, params: { user: { email: @user.email, password: 'b@d_pa$$' } }, as: :json
    assert_response :unauthorized
  end
end
----

Te estarás preguntando: "¿pero como puedes saber la contraseña del usuario?". Simplemente usa el método `BCrypt::Password.create` en los _fixtures_ de `users`:

.test/fixtures/users.yml
[source,yaml]
----
one:
  email: one@one.org
  password_digest: <%= BCrypt::Password.create('g00d_pa$$') %>
----

En este preciso momento, si corres las pruebas obtendrás dos errores:

[source,bash]
----
$ rake test

........E

Error:
Api::V1::TokensControllerTest#test_should_get_JWT_token:
JSON::ParserError: 767: unexpected token at ''


Failure:
Expected response to be a <401: unauthorized>, but was a <204: No Content>
----

Es normal. Ahora es tiempo de implementar la lógica para crear el token JWT. Es muy sencillo.

.app/controllers/api/v1/tokens_controller.rb
[source,ruby]
----
class Api::V1::TokensController < ApplicationController
  def create
    @user = User.find_by_email(user_params[:email])
    if @user&.authenticate(user_params[:password])
      render json: {
        token: JsonWebToken.encode(user_id: @user.id),
        email: @user.email
      }
    else
      head :unauthorized
    end
  end

  private

  # Only allow a trusted parameter "white list" through.
  def user_params
    params.require(:user).permit(:email, :password)
  end
end
----

Es un montón de código pero es muy simple:

. Siempre filtramos los parámetros con el método `user_params`.
. Recuperamos el usuario con el método `User.find_by_email` (que es un método "mágico" de _Active Record_ mientras el campo `email` esté presente en la base de datos) y recuperamos el usuario
. Usamos el método `User#authenticate` (el cual existe gracias a la gema `bcrypt`) con la contraseña como un parámetro. Bcrypt hará un _hash_ de la contraseña y verifica si coincide con el atributo `password_digest`. La función regresa `true` si todo salió bien, `false` si no.
. Si la contraseña corresponde al _hash_, un JSON conteniendo el _token_ generado con la clase `JsonWebToken` es devuelto. De otro modo, una respuesta vacía es devuelta con una cabecera `unauthorized`

¿Estas hasta aquí? ¡No te preocupes, esta terminado! Ahora tus pruebas deberían pasar.

[source,bash]
----
$ rake test

...........

Finished in 0.226196s, 48.6304 runs/s, 70.7351 assertions/s.
11 runs, 16 assertions, 0 failures, 0 errors, 0 skips
----

¡Muy bien! Es tiempo de hacer un commit que contendrá todos nuestros cambios:

[source,bash]
----
$ git add . && git commit -m "Setup tokens controller"
----


== Usuario logueado

Entonces ya implementamos la siguiente lógica: la API retorna el token de autenticación a el cliente si las credenciales son correctas.

Pero ahora implementaremos la siguiente lógica: encontraremos el usuario correspondiente del token de autenticación proporcionado en la cabecera HTTP. Necesitamos hacerlo cada vez que este cliente solicite un `entry point`  que requiera permisos.

Usaremos la cabecera HTTP `Authorization` que a menudo es usada para este propósito. También podemos usar un parámetro GET llamado `apiKey` pero prefiero usar una cabecera HTTP porque da contexto a la petición sin contaminar la URL con parámetros adicionales.

Por lo tanto, crearemos un método `current_user` para satisfacer nuestras necesidades. Este encontrará el usuario gracias a su token de autenticación que es enviado en cada petición.

Cuando se trata de autenticación, me gusta añadir todos los métodos asociados en un archivo separado. Entonces simplemente incluimos el archivo `ApplicationController`. De este modo, es muy fácil para probar de forma aislada. Vamos a crear el archivo en el directorio `controllers/concerns` con un método `current_user` que implementaremos después:

[source,ruby]
.app/controllers/concerns/authenticable.rb
----
module Authenticable
  def current_user
    # TODO
  end
end
----

Entonces, vamos a crear un directorio `concerns` en `tests/controllers/` y un archivo `authenticable_test.rb` para nuestras pruebas de a autenticación:


[source,bash]
----
$ mkdir test/controllers/concerns
$ touch test/controllers/concerns/authenticable_test.rb
----

Como es usual, iniciamos por escribir nuestra prueba. En este caso, nuestro método `current_user` buscará un usuario por el token de autenticación en la cabecera HTTP `Authorization`. La prueba es muy básica:

[source,ruby]
.test/controllers/concerns/authenticable_test.rb
----
# ...
class AuthenticableTest < ActionDispatch::IntegrationTest
  setup do
    @user = users(:one)
    @authentication = MockController.new
  end

  test 'should get user from Authorization token' do
    @authentication.request.headers['Authorization'] = JsonWebToken.encode(user_id: @user.id)
    assert_equal @user.id, @authentication.current_user.id
  end

  test 'should not get user from empty Authorization token' do
    @authentication.request.headers['Authorization'] = nil
    assert_nil @authentication.current_user
  end
end
----

Te estarás preguntando, "¿De donde viene el controlador `MockController`?", De hecho, éste es un _Mock_, por ejemplo una clase que imita el comportamiento de otra para probar un comportamiento

Podemos definir la clase `MockController` justo sobre nuestra prueba:

[source,ruby]
.test/controllers/concerns/authenticable_test.rb
----
# ...
class MockController
  include Authenticable
  attr_accessor :request

  def initialize
    mock_request = Struct.new(:headers)
    self.request = mock_request.new({})
  end
end
# ...
----

La clase `MockController` simplemente incluye nuestro módulo `Authenticable` que probaremos. Este contiene un atributo `request` que contiene un simple https://ruby-doc.org/core-2.6.3/Struct.html[`Struct`] que imita el comportamiento de una petición Rails conteniendo un atributo `headers` de tipo `Hash`.

Entonces podemos implementar nuestras dos pruebas ahora

[source,ruby]
.test/controllers/concerns/authenticable_test.rb
----
# ...
class AuthenticableTest < ActionDispatch::IntegrationTest
  setup do
    @user = users(:one)
    @authentication = MockController.new
  end

  test 'should get user from Authorization token' do
    @authentication.request.headers['Authorization'] = JsonWebToken.encode(user_id: @user.id)
    assert_not_nil @authentication.current_user
    assert_equal @user.id, @authentication.current_user.id
  end

  test 'should not get user from empty Authorization token' do
    @authentication.request.headers['Authorization'] = nil
    assert_nil @authentication.current_user
  end
end
----

Nuestra prueba debería fallar. Así que vamos a implementar el código para que ésta pase:

[source,ruby]
.app/controllers/concerns/authenticable.rb
----
module Authenticable
  def current_user
    return @current_user if @current_user

    header = request.headers['Authorization']
    return nil if header.nil?

    decoded = JsonWebToken.decode(header)

    @current_user = User.find(decoded[:user_id]) rescue ActiveRecord::RecordNotFound
  end
end
----

Ahí tienes! Obtenemos el token desde la cabecera `Authorization` y buscamos el usuario correspondiente. Nada tan mágico.

Nuestra prueba debería pasar:

[source,bash]
----
$ rake test
.............
13 runs, 18 assertions, 0 failures, 0 errors, 0 skips
----

Todo lo que tenemos que hacer es incluir el módulo `Authenticable` en la clase `ApplicationController`:

[source,ruby]
.app/controllers/application_controller.rb
----
class ApplicationController < ActionController::API
  # ...
  include Authenticable
end
----

Y ahora es tiempo de hacer _commit_  a nuestros cambios:

[source,bash]
----
$ git add . && git commit -m "Adds authenticable module for managing authentication methods"
----

== Autenticación con el token

La autorización juega un papel importante en la construcción de aplicaciones porque nos ayuda a definir que usuario tiene permisos para continuar.

Tenemos una ruta para actualizar el usuario, pero hay un problema: cualquiera puede actualizar cualquier usuario. En esta sección, vamos a implementar un método que requerirá al usuario estar logueado para prevenir accesos no autorizados.

=== Acciones de autorización

Es tiempo ahora de actualizar nuestro archivo `users_controller.rb` para negar el acceso a ciertas acciones. Vamos también a implementar el método `current_user` en las acciones `update` y `destroy` para asegurarnos que el usuario que esta logueado solo podrá actualizar sus datos y puede únicamente borrar (y solo) su cuenta.

Por lo tanto dividimos nuestra prueba en dos pruebas _should update user_ y _should destroy user_.

Iniciamos por actualizar la prueba _should update user_.

.test/controllers/api/v1/users_controller_test.rb
[source,ruby]
----
# ...
class Api::V1::UsersControllerTest < ActionDispatch::IntegrationTest
  # ...
  test "should update user" do
    patch api_v1_user_url(@user),
      params: { user: { email: @user.email } },
      headers: { Authorization: JsonWebToken.encode(user_id: @user.id) },
      as: :json
    assert_response :success
  end

  test "should forbid update user" do
    patch api_v1_user_url(@user), params: { user: { email: @user.email } }, as: :json
    assert_response :forbidden
  end
end
----

Puedes ver ahora que tenemos que añadir una cabecera _Authorization_ para la acción de modificar usuarios. De lo contrario queremos recibir una respuesta _forbidden_.

Podemos pensar de forma similar para la prueba _should forbid destroy user_:

.test/controllers/api/v1/users_controller_test.rb
[source,ruby]
----
# ...
class Api::V1::UsersControllerTest < ActionDispatch::IntegrationTest
  # ...
  test "should destroy user" do
    assert_difference('User.count', -1) do
      delete api_v1_user_url(@user), headers: { Authorization: JsonWebToken.encode(user_id: @user.id) }, as: :json
    end
    assert_response :no_content
  end

  test "should forbid destroy user" do
    assert_no_difference('User.count') do
      delete api_v1_user_url(@user), as: :json
    end
    assert_response :forbidden
  end
end
----

Por el momento estas pruebas pueden fallar como ya lo podrías esperar:

[source,bash]
----
$ rails test test/controllers/api/v1/users_controller_test.rb
..F

Failure:
Expected response to be a <2XX: success>, but was a <403: Forbidden>

..F

Failure:
"User.count" didn t change by -1.
Expected: 0
  Actual: 1
----

La solución es muy simple. Vamos a añadir un `before_action` el cual llamará al método `check_owner` para las acciones `update` y `destroy`. De esta forma comprobamos que el usuario que corresponde al token JWT es el mismo que el usuario que necesita ser actualizado.

Ésta es la implementación:

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  before_action :set_user, only: %i[show update destroy]
  before_action :check_owner, only: %i[update destroy]
  # ...

  private
  # ...
  def check_owner
    head :forbidden unless @user.id == current_user&.id
  end
end
----

¡Ahí tienes! La implementación es realmente simple. Es por lo tanto tiempo de hacer un _commit_:

[source,bash]
----
$ git commit -am "Restrict actions for unauthorized users"
$ git checkout master
$ git merge chapter04
----

== Conclusión

¡Yeah!, ¡lo hiciste! tienes medio camino terminado! Mantén este buen trabajo. Este capítulo fue largo y difícil pero es un gran paso a seguir para implementar un mecanismo sólido para manipular autenticación de usuarios. Incluso logramos tocar la superficie para implementar reglas simples de autenticación.

En el próximo capítulo nos enfocaremos en la personalización de las salidas JSON para el usuario con la gema https://github.com/Netflix/fast_jsonapi[fast_jsonapi] y añadiremos un modelo `product` a la ecuación dando al usuario la habilidad para crear un producto y publicarlo para su venta.
