[#chapter07-placing-orders]
= Colocando órdenes

En el capítulo previo manejamos asociaciones entre productos y usuarios y como serializarlos a fin de escalar rápido y fácil. Ahora es tiempo de empezar a implementar las ordenes lo cual será una situación algo más compleja. Manejaremos asociaciones entre estos tres modelos. Debemos ser lo suficientemente inteligentes para manejar la salida JSON que estamos entregando.

En este capítulo haremos algunas cosas que están listadas a continuación:

* Crear un modelo `Order` con sus correspondientes especificaciones
* Manipular la salida JSON con asociación entre los modelos orden de usuario y producto
* Enviar un mail de confirmación con el resumen de la orden

Entonces ahora todo está claro podemos ensuciarnos las manos. Puedes clonar el proyecto hasta este punto con:

[source,bash]
----
$ git checkout tags/checkpoint_chapter07
----

Creemos una rama para empezar a trabajar:

[source,bash]
----
$ git checkout -b chapter07
----

== Modelando la orden

Si recuerdas asociaciones de modelos, el modelo `Order` esta asociado con usuarios y productos al mismo tiempo. Actualmente esto es muy simple de lograr en Rails. La parte difícil es cuando vamos a serializar estos objetos. Hablare más sobre esto en la siguiente sección.

Vamos a empezar creando el modelo `order` con una forma especial:

[source,bash]
----
$ rails generate model order user:belongs_to total:decimal
----

El comando anterior generará el modelo order pero estoy tomando ventaja del método `references` para crear la llave foránea correspondiente para que la orden pertenezca a el usuario. Esto también añade la directiva `belongs_to` dentro del modelo. Vamos a migrar la base de datos.

[source,bash]
----
$ rake db:migrate
----

Ahora es tiempo para escribir algunas pruebas dentro del archivo`order_test.rb`:

[source,ruby]
.test/models/order_test.rb
----
# ...
class OrderTest < ActiveSupport::TestCase
  test 'Should have a positive total' do
    order = orders(:one)
    order.total = -1
    assert_not order.valid?
  end
end
----

La implementación es demasiado simple:

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  belongs_to :user
  validates :total, numericality: { greater_than_or_equal_to: 0 }
  validates :total, presence: true
end
----

No olvides añadir la relación `orders` a nuestros usuarios especificando el borrado en cascada:

[source,ruby]
.app/models/user.rb
----
class User < ApplicationRecord
  # ...
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  # ...
end
----

Las pruebas deberían pasar:

[source,bash]
----
$ rake test
..................................
----

Y hacemos _commit_ de todo esto:

[source,bash]
----
$ git add . && git commit -m "Generate orders"
----


=== Ordenes y productos

Necesitamos configurar la asociación entre la `order` y el `product` y esto se hace con una asociación *has-many-to-many*. Como muchos productos pueden ser puestos en muchas ordenes y las ordenes puede tener múltiples productos. Así en este caso necesitamos un modelo intermedio el cual unirá estos otros dos objetos y mapeará las asociaciones apropiadas.

Vamos a genera este modelo:

[source,bash]
----
$ rails generate model placement order:belongs_to product:belongs_to
----

Vamos a correr la migración en la base de datos:

[source,bash]
----
$ rake db:migrate
----

La implementación es como:

[source,ruby]
.app/models/product.rb
----
class Product < ApplicationRecord
  belongs_to :user
  has_many :placements, dependent: :destroy
  has_many :orders, through: :placements
  # ...
end
----

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  has_many :placements, dependent: :destroy
  has_many :products, through: :placements
  # ...
end
----

Si has estado siguiendo el tutorial para la implementación , esta ya está lista debido a las `references` (referencias) que forman parte del comando generador del modelo. Podríamos añadir la opción `inverse_of` a el modelo `placement` para cada llamada `belongs_to`. Esto da un pequeño impulso cuando referenciamos al objeto padre.

[source,ruby]
.app/models/placement.rb
----
class Placement < ApplicationRecord
  belongs_to :order
  belongs_to :product, inverse_of: :placements
end
----

Vamos a correr las pruebas de los _modelos_ y asegurar que todo es verde:

[source,bash]
----
$ rake test
..................................
----

Ahora que todo está bien y en verde vamos a hacer commit de los cambios y continuar.

[source,bash]
----
$ git add . && git commit -m "Associates products and orders with a placements model"
----


== Exponer el modelo usuario

Es tiempo de poner en orden el controlador para exponer las ordenes correctas. Si recuerdas el capítulo previo donde https://github.com/Netflix/fast_jsonapi_jsonapi[fast_jsonapi] fue usada, deberías recordar que fue realmente fácil.

Vamos a definir primero que acciones tomará:

. Una acción de indexación para recuperar las ordenes de usuario actuales
. Una acción show para recuperar un comando particular desde el usuario actual
. Una acción de creación para generar la orden

Vamos a iniciar con la acción `index`. Primero tenemos el comando para crear el controlador:

[source,bash]
----
$ rails generate controller api::v1::orders
----

Hasta este punto y antes de empezar a escribir algo de código tenemos que preguntarnos a nosotros mismos:

> ¿Debería dejar mis enpoints de ordenes anidado dentro de `UserController` o debería aislarlas?

La respuesta es realmente simple: esto depende de la carga o información que quieras exponer al desarrollador.

En nuestro caso, no haremos esto porque recuperaremos los comandos del usuario desde la ruta `/orders`. Vamos a iniciar con algunas pruebas:

[source,ruby]
.test/controllers/api/v1/orders_controller_test.rb
----
# ...
class Api::V1::OrdersControllerTest < ActionDispatch::IntegrationTest
  setup do
    @order = orders(:one)
  end

  test 'should forbid orders for unlogged' do
    get api_v1_orders_url, as: :json
    assert_response :forbidden
  end

  test 'should show orders' do
    get api_v1_orders_url,
      headers: { Authorization: JsonWebToken.encode(user_id: @order.user_id) },
      as: :json
    assert_response :success

    json_response = JSON.parse(response.body)
    assert_equal @order.user.orders.count, json_response['data'].count
  end
end
----

Si corremos la suit de pruebas ahora ambas pruebas deberían de fallar como ya esperábamos. Esto es porque estas no tienen establecidas las rutas o acciones correctas. Iniciemos añadiendo las rutas:

[source,ruby]
.config/routes.rb
----
Rails.application.routes.draw do
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :orders, only: [:index]
      # ...
    end
  end
end
----

Ahora es tiempo para implementar la serialización de las ordenes:



[source,bash]
----
$ rails generate serializer Order
----

Y vamos a añadir relaciones:

.app/serializers/order_serializer.rb
[source,ruby]
----
class OrderSerializer
  include FastJsonapi::ObjectSerializer
  belongs_to :user
  has_many :products
end
----

Ahora es tiempo de implementar el controlador:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  before_action :check_login, only: %i[index]

  def index
    render json: OrderSerializer.new(current_user.orders).serializable_hash
  end
end
----

Y ahora todas nuestras pruebas deberían de pasar:

[source,bash]
----
$ rake test
....................................
36 runs, 53 assertions, 0 failures, 0 errors, 0 skips
----

Nos gustan que nuestros commits sean muy atómicos, así que vamos a guardar estos cambios:

[source,bash]
----
$ git add . && git commit -m "Adds the index action for order"
----

=== Renderizar una sola orden

Como ahora puedes imaginar esta ruta es muy fácil. Únicamente hacemos algunas configuraciones (rutas, acción de controlador) y esta sección estará terminada. También incluiremos productos relacionados a esta orden en la salida JSON.

Vamos a iniciar añadiendo algunas pruebas:

[source,ruby]
.test/controllers/api/v1/orders_controller_test.rb
----
# ...
class Api::V1::OrdersControllerTest < ActionDispatch::IntegrationTest
  # ...
  test 'should show order' do
    get api_v1_order_url(@order),
        headers: { Authorization: JsonWebToken.encode(user_id: @order.user_id) },
        as: :json
    assert_response :success

    json_response = JSON.parse(response.body)
    include_product_attr = json_response['included'][0]['attributes']
    assert_equal @order.products.first.title, include_product_attr['title']
  end
end
----

Como puedes ver, la segunda parte de la prueba verifica que el producto está incluido en el JSON.

Vamos añadir la implementación para correr nuestras pruebas. En el archivo `routes.rb` añadimos la acción `show` a las rutas de comando:

[source,ruby]
.config/routes.rb
----
# ...
Rails.application.routes.draw do
  # ...
  resources :orders, only: %i[index show]
  # ...
end
----

Y la implementación debería lucir como esto:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  before_action :check_login, only: %i[index show]
  # ...
  def show
    order = current_user.orders.find(params[:id])

    if order
      options = { include: [:products] }
      render json: OrderSerializer.new(order, options).serializable_hash
    else
      head 404
    end
  end
end
----

Nuestras pruebas deberían estar todas verdes:

[source,bash]
----
$ rake test
.....................................
37 runs, 55 assertions, 0 failures, 0 errors, 0 skips
----

Vamos a hacer commit de los cambios y parar a crear la acción de crear orden:

[source,bash]
----
$ git commit -am "Adds the show action for order"
----

=== Colocando y ordenando

Es tiempo ahora de dar la oportunidad de colocar algunas órdenes. Esto añadirá complejidad a la aplicación, pero no te preocupes, vamos a hacer cada cosa en su tiempo.

Antes de implementar esta característica, tomare tiempo para pensar sobre la implicación de crear un comando en la aplicación. No estoy hablando sobre configurar un servicio de transacción como el de https://stripe.com/[Stripe] ó https://www.braintreepayments.com/[Braintree] pero algo como:

* gestionamiento de productos out-of-stock (fuera de stock)
* reducir el inventario del producto
* añadir alguna validación para el colocamiento de ordenes para asegurar que hay los suficientes productos al momento de colocar la orden

Parece que aún hay mucho por hacer pero créeme: estar más cerca de lo que piensas y no es tan difícil como parece. Por ahora mantengámoslo simple y asumamos que aún tendremos suficientes productos para colocar cualquier número de órdenes. Solo estamos preocupados sobre la respuesta del servidor por el momento.

Si tu recuerdas el modelo de orden, necesitamos tres cosas:

* un total para la orden
* usuario que coloca la orden
* productos para la orden

Basado en esta información podemos empezar añadiendo algunas pruebas:

[source,ruby]
.test/controllers/api/v1/orders_controller_test.rb
----
# ...
class Api::V1::OrdersControllerTest < ActionDispatch::IntegrationTest
  setup do
    # ...
    @order_params = { order: {
      product_ids: [products(:one).id, products(:two).id],
      total: 50
    } }
  end

  # ...

  test 'should forbid create order for unlogged' do
    assert_no_difference('Order.count') do
      post api_v1_orders_url, params: @order_params, as: :json
    end
    assert_response :forbidden
  end

  test 'should create order with two products' do
    assert_difference('Order.count', 1) do
      post api_v1_orders_url,
        params: @order_params,
        headers: { Authorization: JsonWebToken.encode(user_id: @order.user_id) },
        as: :json
    end
    assert_response :created
  end
end
----

Como puedes ver estamos crean una variable `order_params` con los datos de la orden. ¿Puedes ver el problema aquí? Si no, lo explicare más tarde. Justamente añadimos el código necesario para hacer pasar la prueba.

Primero necesitamos añadir la acción a los recursos en el archivo de rutas:

[source,ruby]
.config/routes.rb
----
# ...
Rails.application.routes.draw do
  # ...
  resources :orders, only: %i[index show create]
  # ...
end
----

Entonces la implementación es fácil:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  before_action :check_login, only: %i[index show create]
  # ...

  def create
    order = current_user.orders.build(order_params)

    if order.save
      render json: order, status: 201
    else
      render json: { errors: order.errors }, status: 422
    end
  end

  private

  def order_params
    params.require(:order).permit(:total, product_ids: [])
  end
end
----

Y ahora nuestras pruebas deberian estar en verde:

[source,bash]
----
$ rake test
.......................................
39 runs, 59 assertions, 0 failures, 0 errors, 0 skips
----

Ok, entonces tenemos todo correcto y en verde. Ahora deberíamos movernos al siguiente capitulo, ¿correcto? Déjame detenerte justo aquí. Tenemos algunos errores serios en la aplicación, y estos no están relacionados al código por sí mismo, pero si en la parte del negocio.

No porque los las pruebas estén verdes, esto significa que la aplicación esta cubriendo la parte del negocio. Quería traer esto aquí porque en muchos casos es super fácil solo recibir parámetros y construir objetos desde esos parámetros pensando que siempre estamos recibiendo los datos correctos. En este caso particular no podemos confiar en eso, y la forma fácil de ver esto, es que le estamos dando al cliente la oportunidad de poner el total, ¡que locura!

Tenemos que añadir algunas validaciones o un callback para calcular el total de la orden y colocarlo entre el modelo. De esta forma ya no recibiremos más el atributo del total y asi tener el control total sobre este atributo. Vamos a hacer esto:

Primer necesitamos algunas especificaciones a el modelo de la orden:

[source,ruby]
.test/models/order_test.rb
----
# ...
class OrderTest < ActiveSupport::TestCase

  setup do
    @order = orders(:one)
    @product1 = products(:one)
    @product2 = products(:two)
  end

  test 'Should set total' do
    order = Order.new user_id: @order.user_id
    order.products << products(:one)
    order.products << products(:two)
    order.save

    assert_equal (@product1.price + @product2.price), order.total
  end
end
----

Ahora podemos añadir la implementación:

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  # ...
  def set_total!
    self.total = products.map(&:price).sum
  end
end
----

Ahora podemos incluir el método `set_total!` a un callback `before_validation` para asegurar que tiene el total correcto antes de ser validado.

[source,ruby]
.app/models/order.rb
----
class Order < ApplicationRecord
  before_validation :set_total!
  # ...
end
----

Hasta este punto nos aseguramos que el total está siempre presente y es mayor o igual a cero. Esto significa que podemos quitar esas validaciones y quitar las especificaciones. Esperaré. Nuestras pruebas deberían pasar por ahora:

[source,bash]
----
$ rake test

...........F

Failure:
OrderTest#test_Should_have_a_positive_total [/home/arousseau/github/madeindjs/market_place_api/test/models/order_test.rb:14]:
Expected true to be nil or false


rails test test/models/order_test.rb:11

............................

Finished in 0.542600s, 73.7191 runs/s, 110.5786 assertions/s.
----


¡Oops! Obtuvimos un _failure_ (falla) en nuestra anterior prueba _Should have a positive total_. Es lógico desde que el total de la orden es calculado dinámicamente. Así que podemos simplemente quitar esta prueba que ha quedado obsoleta.

Nuestra prueba debería pasar. Guardemos nuestros cambios:

[source,bash]
----
$ git commit -am "Adds the create method for the orders controller"
----


== Enviar email de confirmación de la orden

La última sección para este capítulo es para enviar el mail de confirmación al usuario que ordenó. Si quiere saltar esta parte e ir al siguiente capítulo hazlo. Esta sección es más como un calentamiento.

Tal vez estas familiarizado con la manipulación de emails con Rails así que intentaremos hacer esto fácil y rápido. Primero creamos el `order_mailer` con un email llamado `send_confirmation`:

[source,bash]
----
$ rails generate mailer order_mailer send_confirmation
----

Ahora agregamos algunas pruebas para los correos de la orden que acabamos de crear:

[source,ruby]
.test/mailers/order_mailer_test.rb
----
# ...
class OrderMailerTest < ActionMailer::TestCase

  setup do
    @order = orders(:one)
  end

  test "should be set to be delivered to the user from the order passed in" do
    mail = OrderMailer.send_confirmation(@order)
    assert_equal "Order Confirmation", mail.subject
    assert_equal [@order.user.email], mail.to
    assert_equal ['no-reply@marketplace.com'], mail.from
    assert_match "Order: ##{@order.id}", mail.body.encoded
    assert_match "You ordered #{@order.products.count} products", mail.body.encoded
  end

end
----

Yo simplemente copie/pegue las pruebas desde la documentación y las adapte a nuestras necesidades. Ahora nos aseguramos que estas pruebas pasan.

Primero, añadimos el método `OrderMailer#send_confirmation`:

[source,ruby]
.app/mailers/order_mailer.rb
----
class OrderMailer < ApplicationMailer
  default from: 'no-reply@marketplace.com'
  def send_confirmation(order)
    @order = order
    @user = @order.user
    mail to: @user.email, subject: 'Order Confirmation'
  end
end
----

Después de añadir este código añadimos las vistas correspondientes. Es una buena práctica incluir un texto de la versión como extra a la versión HTML.


[source,erb]
----
<%# app/views/order_mailer/send_confirmation.text.erb %>
Order: #<%= @order.id %>
You ordered <%= @order.products.count %> products:
<% @order.products.each do |product| %>
  <%= product.title %> - <%= number_to_currency product.price %>
<% end %>
----

[source,erb]
----
<!-- app/views/order_mailer/send_confirmation.html.erb -->
<h1>Order: #<%= @order.id %></h1>
<p>You ordered <%= @order.products.count %> products:</p>
<ul>
  <% @order.products.each do |product| %>
    <li><%= product.title %> - <%= number_to_currency product.price %></li>
  <% end %>
</ul>
----

Ahora, nuestra prueba debería pasar:

[source,bash]
----
$ rake test
........................................
40 runs, 66 assertions, 0 failures, 0 errors, 0 skips
----

Y ahora, solo llamamos al método `OrderMailer#send_confirmation` en la acción de crear en el controlador de la orden:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  # ...
  def create
    order = current_user.orders.build(order_params)

    if order.save
      OrderMailer.send_confirmation(order).deliver
      render json: order, status: 201
    else
      render json: { errors: order.errors }, status: 422
    end
  end
  # ...
end
----

Para asegurar que no rompimos nada, vamos a correr todas las pruebas:

[source,bash]
----
$ rake test
........................................
40 runs, 66 assertions, 0 failures, 0 errors, 0 skips
----

Hagamos commit a todo para ya que está completa esta sección:

[source,bash]
----
$ git add . && git commit -m "Adds order confirmation mailer"
----

Y como hemos llegado al final de nuestro capítulo, es tiempo de aplicar todas nuestras modificaciones a la rama master haciendo un `merge':

[source,bash]
----
$ git checkout master
$ git merge chapter07
----

== Conclusión

¡Eso es! ¡Lo hiciste! Puedes aplaudirte. Se que fue un largo tiempo pero créeme estas casi terminando.

En siguientes capítulos continuaremos trabajando en la plantilla de la orden y añadir validaciones cuando se hace una orden. Algunos escenarios son:

* Que pasa cuando los productos no están disponibles?
* Reducir la cantidad de los productos en progreso cuando se está ordenando

El siguiente capítulo será corto, pero es muy importante para la salud de la aplicación. así que no te lo saltes.
