[#chapter05-authentication]
= Authentification des utilisateurs

Cela fait longtemps que vous avez commencé. J’espère que vous appréciez ce voyage autant que moi. Au chapitre 4, nous avons factorisé notre suite de tests et, comme nous n’avons pas ajouté beaucoup de code, cela n’a pas pris trop de temps. Si vous avez sauté ce chapitre, je vous recommande de le lire, car nous allons utiliser certaines méthodes dans les chapitres à venir.

Vous pouvez cloner le projet jusqu’ici:

[source,bash]
----
$ git clone --branch chapitre_4 https://github.com/madeindjs/market_place_api
----

Dans ce chapitre, les choses vont devenir plus intéressantes. Nous allons mettre en place notre mécanisme d’authentification. À mon avis, ce sera l’un des chapitres les plus intéressants car nous allons introduire beaucoup de nouveaux concepts. A la fin, vous aurez un système d’authentification simple mais puissant. Ne paniquez pas, nous y arriverons.

Commençons par le commencement. Comme d’habitude quand nous démarrons un nouveau chapitre, nous allons créer une nouvelle branche:

[source,bash]
----
$ git checkout -b chapter5
----

== Session sans état

Avant d’aller plus loin, quelque chose doit être clair: *une API ne gère pas les sessions*. Si vous n’avez pas d’expérience dans la création de ce genre d’applications, cela peut paraître un peu fou. Une API doit être sans état. Ce qui signifie par définition qu’il s’agit d’une API qui fournit une réponse après votre demande et qui ne nécessite aucune autre attention. Cela à pour conséquence qu’aucun état antérieur ou futur n’est nécessaire pour que le système fonctionne.

Le processus d’authentification de l’utilisateur via une API est très simple:

. Le client *demande* une ressource de sessions avec les informations d’identification correspondantes (généralement un e-mail et un mot de passe).
. Le serveur *renvoie* la ressource utilisateur avec son jeton d’authentification correspondant.
. Pour chaque page qui nécessite une authentification, le client doit envoyer ce jeton d’authentification.

Dans cette section et la suivante, nous nous concentrerons sur la construction d’un contrôleur de sessions avec ses actions correspondantes. Nous compléterons ensuite le flux de demandes en ajoutant l’accès d’autorisation nécessaire.

=== Le jeton d’authentification

Avant de procéder à la logique sur le contrôleur de sessions, nous devons d’abord ajouter le champ du jeton d’authentification au modèle utilisateur. Ensuite, il faudra ajouter une méthode pour définir ce jeton.

Nous commençons donc par générer un fichier de migration:

[source,bash]
----
$ rails generate migration add_authentification_token_to_users auth_token:string
----

Comme une bonne pratique, j’aime configurer les valeurs `String` à une chaîne vide. Et dans ce cas, nous allons ajouter un index avec une condition d’unicité. Ainsi, nous garantissons qu’il n’y a pas d’utilisateurs avec le même jeton. Alors faisons-le:

[source,ruby]
.db/migrate/20181114134521_add_authentification_token_to_users.rb
----
class AddauthentificationTokenToUsers < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :auth_token, :string, default: ''
    add_index :users, :auth_token, unique: true
  end
end
----

Ensuite, nous exécutons les migrations pour ajouter le champ et préparer la base de données de test:

[source,bash]
----
$ rake db:migrate
== 20181114134521 AddauthentificationTokenToUsers: migrating ====================
-- add_column(:users, :auth_token, :string, {:default=>""})
   -> 0.0004s
-- add_index(:users, :auth_token, {:unique=>true})
   -> 0.0010s
== 20181114134521 AddauthentificationTokenToUsers: migrated (0.0016s) ===========
----

Il est maintenant temps d’ajouter quelques tests de réponse et d’unicité à nos spécifications de modèle utilisateur.

[source,ruby]
.spec/models/user_spec.rb
----
RSpec.describe User, type: :model do
  # ...
  it { should respond_to(:auth_token) }
  it { should validate_uniqueness_of(:auth_token)}
end
----

Nous passons ensuite au fichier `user.rb` et ajoutons le code nécessaire pour faire passer nos tests:

[source,ruby]
.app/models/user.rb
----
class User < ApplicationRecord
  validates :auth_token, uniqueness: true
  # ...
end
----

Maintenant nous allons implémenter une méthode qui générera un jeton d’authentification unique pour chaque utilisateur afin de les authentifier plus tard via l’API. Construisons donc d’abord les tests.

[source,ruby]
.spec/models/user_spec.rb
----
RSpec.describe User, type: :model do
  # ...
  describe "#generate_authentification_token!" do
    it "generates a unique token" do
      @user.generate_authentification_token!
      expect(@user.auth_token).not_to be_nil
    end

    it "generates another token when one already has been taken" do
      existing_user = FactoryBot.create(:user, auth_token: "auniquetoken123")
      @user.generate_authentification_token!
      expect(@user.auth_token).not_to eql existing_user.auth_token
    end
  end
end
----

Afin d’utiliser la méthode `validate_uniqueness_of`, il faut installer la gemme `shoulda-matchers`. Pour cela, nous rajoutons la gemme dans le `Gemfile`:

[source,ruby]
.Gemfile
----
# ...
group :test do
  # ...
  gem 'shoulda-matchers'
end
----

Et nous la chargeons dans le fichier `rails_helper.rb`:

[source,ruby]
.spec/rails_helper.rb
----
# ...
RSpec.configure do |config|
  # ...
  RSpec.configure do |config|
    config.include(Shoulda::Matchers::ActiveModel, type: :model)
    config.include(Shoulda::Matchers::ActiveRecord, type: :model)
  end
end
----

Les tests échouent comme prévu:

....
$ bundle exec rspec spec/models/user_spec.rb
.......FF

Failures:

  1) User#generate_authentification_token! generates a unique token
     Failure/Error: @user.generate_authentification_token!

     NoMethodError:
       undefined method `generate_authentification_token!' for #<User:0x0000558948d23760>
     # ./spec/models/user_spec.rb:23:in `block (3 levels) in <top (required)>'

  2) User#generate_authentification_token! generates another token when one already has been taken
     Failure/Error: @user.generate_authentification_token!

     NoMethodError:
       undefined method `generate_authentification_token!' for #<User:0x0000558948d18720>
     # ./spec/models/user_spec.rb:29:in `block (3 levels) in <top (required)>'
....

C’est normal: la méthode `generate_authentification_token` n’existe pas encore. Nous allons l’implémenter et l’accrocher à l’appel `before_create` pour garantir que chaque utilisateur a un jeton d’authentification. Il y a beaucoup de solutions pour créer le jeton. Je vais utiliser la méthode `friendly_token` qui conçoit déjà des jetons mais je pourrais aussi le faire avec la méthode `hex` de la classe https://ruby-doc.org/stdlib-2.5.3/libdoc/securerandom/rdoc/SecureRandom.html[`SecureRandom`].

Le code pour générer le jeton est assez simple:

[source,ruby]
.app/models/user.rb
----
class User < ApplicationRecord
  before_create :generate_authentification_token!
  # ...
  def generate_authentification_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end
end
----

Après avoir fait cela, nous tests devraient passer:

[source,bash]
----
$ bundle exec rspec spec/models/user_spec.rb
.........

Finished in 0.05079 seconds (files took 0.49029 seconds to load)
9 examples, 0 failures
----

Comme d’habitude, nous _commitons_ nos modifications:

[source,bash]
----
$ git add .
$ git commit -m "Adds user authentification token"
----

=== Le contrôleur de session

De retour au contrôleur de sessions. Les actions que nous allons implémenter seront gérées en tant que services _RESTful_: la connexion sera gérée par une demande POST à l’action `create` et la déconnexion par une demande `DELETE` à l’action `destroy`.

Pour commencer, nous allons commencer par créer le contrôleur de sessions:

[source,bash]
----
$ rails generate controller sessions
----

Ensuite, nous devons déplacer les fichiers dans le répertoire `api/v1`, à la fois pour le dossier `app` mais aussi pour le dossier `spec`:

[source,bash]
----
$ mv app/controllers/sessions_controller.rb app/controllers/api/v1
$ mv spec/controllers/sessions_controller_spec.rb spec/controllers/api/v1
----

Après avoir déplacé les fichiers, nous devons les mettre à jour pour qu’ils correspondent à la structure des répertoires que nous avons actuellement, comme le montrent les listing suivants.

[source,ruby]
.app/controllers/api/v1/sessions_controller.rb
----
class Api::V1::SessionsController < ApplicationController
end
----

[source,ruby]
.spec/controllers/api/v1/sessions_controller_spec.rb
----
# ...
RSpec.describe Api::V1::SessionsController, type: :controller do
end
----

==== Connexion réussie

Notre premier arrêt sera l’action de création. Mais d’abord, et comme d’habitude, générons nos tests.

[source,ruby]
.spec/controllers/api/v1/sessions_controller_spec.rb
----
# ...
RSpec.describe Api::V1::SessionsController, type: :controller do
  describe 'POST #create' do
    before(:each) do
      @user = FactoryBot.create :user
    end

    context 'when the credentials are correct' do
      before(:each) do
        post :create, params: {
          session: { email: @user.email, password: '12345678' }
        }
      end

      it 'returns the user record corresponding to the given credentials' do
        @user.reload
        expect(json_response[:auth_token]).to eql @user.auth_token
      end

      it { expect(response.response_code).to eq(200) }
    end

    context 'when the credentials are incorrect' do
      before(:each) do
        post :create, params: {
          session: { email: @user.email, password: 'invalidpassword' }
        }
      end

      it 'returns a json with an error' do
        expect(json_response[:errors]).to eql 'Invalid email or password'
      end

      it { expect(response.response_code).to eq(422) }
    end
  end
end
----

Les tests sont assez simples. Nous renvoyons simplement l’utilisateur au format JSON si les informations d’identification sont correctes, sinon nous envoyons simplement un JSON avec le message d’erreur.

Nous devons maintenant implémenter le code pour que nos tests passent. Mais avant cela, nous ajouterons les routes à notre fichier `route.rb`.

[source,ruby]
.config/routes.rb
----
# ...
Rails.application.routes.draw do
  # ...
  resources :sessions, :only => [:create, :destroy]
end
----

[source,ruby]
.app/controllers/api/v1/sessions_controller.rb
----
class Api::V1::SessionsController < ApplicationController
  def create
    user_password = params[:session][:password]
    user_email = params[:session][:email]
    user = user_email.present? && User.find_by(email: user_email)

    if user.valid_password? user_password
      sign_in user
      user.generate_authentification_token!
      user.save
      render json: user, status: 200, location: [:api, user]
    else
      render json: { errors: 'Invalid email or password' }, status: 422
    end
  end
end
----

Avant d’exécuter nos tests, il est nécessaire d’ajouter les `helpers` dans le fichier `rails_helper.rb`:

[source,ruby]
.spec/rails_helper.rb
----
# ...
RSpec.configure do |config|
  # ...
  config.include Devise::Test::ControllerHelpers, :type => :controller
end
----

Et maintenant nous pouvons lancer nos tests:

[source,bash]
----
$ bundle exec rspec spec/controllers/api/v1/sessions_controller_spec.rb
....

Finished in 0.06515 seconds (files took 0.49218 seconds to load)
4 examples, 0 failures
----

Ourah! Faisons un `commit`:

[source,bash]
----
$ git add .
$ git commit -m "Adds sessions controller create action"
----

==== Déconnexion

Nous avons maintenant l’entrée de l’API. Il est temps de construire un point de sortie. Vous vous demandez peut-être pourquoi, puisque nous ne gérons pas les sessions et qu’il n’y a rien à détruire. Et c’est bien vrai! Lors d’une destruction, nous devons mettre à jour le jeton d’authentification pour que ce dernier devienne inutile et ne puisse plus être utilisé.

Il n’est en fait pas nécessaire d’inclure ce point final, mais j’aime l’inclure pour expirer les jetons d’authentification.

Comme d’habitude, nous commençons par les tests:

[source,ruby]
.spec/controllers/api/v1/sessions_controller_spec.rb
----
# ...
RSpec.describe Api::V1::SessionsController, type: :controller do
  # ...
  describe "DELETE #destroy" do

    before(:each) do
      @user = FactoryBot.create :user
      sign_in @user, store: false
      delete :destroy, params: { id: @user.auth_token }
    end

    it { expect(response.response_code).to eq(204) }

  end
end
----

Comme vous pouvez le voir le test est super simple! Maintenant nous avons juste besoin d’implémenter le code nécessaire pour faire passer nos tests:

[source,ruby]
.app/controllers/api/v1/sessions_controller.rb
----
class Api::V1::SessionsController < ApplicationController
  # ...
  def destroy
    user = User.find_by(auth_token: params[:id])
    user.generate_authentication_token!
    user.save
    head 204
  end
end
----

Ici, nous nous attendons à ce qu’un identifiant soit envoyé sur la requête (qui doit correspondre au jeton d’authentification de l’utilisateur). Nous ajouterons une méthode `current_user` pour gérer cela plus facilement plus tard. Pour l’instant, _commitons_ notre avancée:

[source,bash]
----
$ git add .
$ git commit -m "Adds destroy session action added"
----

== Utilisateur connecté

Si vous avez déjà travaillé avec https://github.com/plataformatec/devise[devise], vous connaissez sûrement déjà les méthodes générées pour gérer l’authentification ou bien pour obtenir l’utilisateur connecté (voir la https://github.com/plataformatec/devise#getting-started[documentation]).

Dans notre cas, nous allons remplacer la méthode `current_user` pour répondre à nos besoins. C’est-à-dire retrouver l’utilisateur grâce à son jeton d’authentification qui est envoyé sur chaque requête. Laissez moi clarifier ce point.

Une fois que le client se connecte, l’API lui retourne son jeton d’authentification. A chaque fois que ce client demande une page protégée, nous devrons retrouver l’utilisateur à partir de ce jeton d’authentification que l’utilisateur aura passé en paramètre ou dans l’en-tête HTTP.

Dans notre cas, nous utiliserons l’en-tête HTTP `Authorization` qui est souvent utilisé pour ça. Personnellement, je le trouve que c’est la meilleure manière parce que cela donne un contexte à la requête sans polluer l’URL avec des paramètres supplémentaires.

Quand il s’agit de l’authentification, j’aime ajouter toutes les méthodes associées dans un fichier séparé. Il suffit ensuite d’inclure le fichier dans le `ApplicationController`. De cette façon, il est très facile à tester de manière isolée. Créons-donc le fichier dans le répertoire `controllers/concerns`:

[source,bash]
----
$ touch app/controllers/concerns/authenticable.rb
----

Ensuite, créons un répertoire `concerns` sous `spec/controllers/` et un fichier `authenticable_spec.rb` pour nos tests d’authentification:

[source,bash]
----
$ mkdir spec/controllers/concerns
$ touch spec/controllers/concerns/authenticable_spec.rb
----

Comme d’habitude, nous commençons par écrire nos tests. Dans ce cas, notre méthode `current_user` va chercher un utilisateur par le jeton d’authentification dans l’en-tête HTTP `Authorization`.

[source,ruby]
.spec/controllers/concerns/authenticable_spec.rb
----
# ...
class Authentication < ActionController::API
  include Authenticable
end

RSpec.describe Authenticable do
  let(:authentication) { Authentication.new }
  subject { authentication }

  describe "#current_user" do
    before do
      @user = FactoryBot.create :user
      request.headers["Authorization"] = @user.auth_token
      authentication.stub(:request).and_return(request)
    end
    it "returns the user from the authorization header" do
      expect(authentication.current_user.auth_token).to eql @user.auth_token
    end
  end
end
----

Notre test doivent échouer. Implémentons donc le code pour qu’il passe:

[source,ruby]
.app/controllers/concerns/authenticable.rb
----
module Authenticable
  # Devise methods overwrites
  def current_user
    @current_user ||= User.find_by(auth_token: request.headers['Authorization'])
  end
end
----

Maintenant notre test devrait passer:

[source,bash]
----
$ rspec spec/controllers/concerns/authenticable_spec.rb
.

Finished in 0.0149 seconds (files took 0.49496 seconds to load)
1 example, 0 failures
----

Nous n’avons plus qu’à inclure le module `Authenticable` dans la classe `ApplicationController`:

[source,ruby]
.app/controllers/application_controller.rb
----
class ApplicationController < ActionController::API
  # ...
  include Authenticable
end
----

Et maintenant il est temps de _commiter_ nos changements:

[source,bash]
----
$ git add .
$ git commit -m "Adds authenticable module for managing authentication methods"
----

== Authentification avec le jeton

L’autorisation joue un rôle important dans la construction des applications car, contrairement à l’authentification qui permet d’identifier l’utilisateur, l’autorisation nous aide à définir ce qu’il a le droit de faire.

Nous avons une route pour mettre à jour l’utilisateur mais il y a un problème: n’importe qui peut mettre à jour n’importe quel utilisateur. Dans cette section, nous allons mettre en œuvre une méthode qui exigera que l’utilisateur soit connecté afin d’empêcher tout accès non autorisé. Nous retournerons un message d’erreur JSON avec un code HTTP correspondant.

Tout d’abord, nous allons ajouter quelques tests sur le fichier `authenticable_spec.rb` pour la méthode `authenticate_with_token` .

[source,ruby]
.spec/controllers/concerns/authenticable_spec.rb
----
# ...
class Authentication < ActionController::API
  include Authenticable
end

RSpec.describe Authenticable do
  # ...
  describe '#authenticate_with_token' do
    before do
      @user = FactoryBot.create :user
      authentication.stub(:current_user).and_return(nil)
      response.stub(:response_code).and_return(401)
      response.stub(:body).and_return({ 'errors' => 'Not authenticated' }.to_json)
      authentication.stub(:response).and_return(response)
    end

    it 'render a json error message' do
      expect(json_response[:errors]).to eql 'Not authenticated'
    end

    it { expect(response.response_code).to eq(401) }
  end
end
----

Comme vous pouvez le voir, nous utilisons à nouveau la classe Authentification et nous écrasons la requête et la réponse pour traiter la réponse attendue du serveur. Il est maintenant temps d’implémenter le code pour faire passer nos tests.

[source,ruby]
.app/controllers/concerns/authenticable.rb
----
module Authenticable
  # ...
  def authenticate_with_token!
    unless current_user.present?
      render json: { errors: 'Not authenticated' },
             status: :unauthorized
    end
  end
end
----

A ce stade, nous venons de construire un mécanisme d’autorisation très simple pour empêcher les utilisateurs non signés d’accéder à l’API. Il suffit de mettre à jour le fichier `users\_controller.rb` avec la méthode `current_user` et d’empêcher l’accès avec la commande `authenticate_with_token!`!

_Commitons_ ces changements et continuons d’avancer:

[source,bash]
----
$ git commit -m "Adds the authenticate with token method to handle access to actions"
----

== Autoriser les actions

Il est maintenant temps de mettre à jour notre fichier `users_controller.rb` pour refuser l’accès à certaines actions. Nous allons aussi implémenter la méthode `current_user` sur l’action `update` et `destroy` afin de s’assurer que l’utilisateur qui est connecté ne sera capable de mettre à jour que ses données et qu’il ne pourra supprimer que (et uniquement) son compte.

Nous allons commencer par l’action `update`. Nous n’irons plus chercher l’utilisateur par son identifiant mais par l’ `auth_token` sur l’en-tête `Authorization` fourni par la méthode `current_user`.

[source,ruby]
----
# app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  # ...
  def update
    # on change juste la methode ici
    user = current_user

    if user.update(user_params)
      render json: user, status: 200, location: [:api, user]
    else
      render json: { errors: user.errors }, status: 422
    end
  end
  # ...
end
----

Et comme vous pouvez vous y attendre, si nous exécutons les tests de notre _controller_ utilisateurs, ils devraient échouer:

....
$ rspec spec/controllers/api/v1/users_controller_spec.rb
.......FFFFF.

Failures:

  1) Api::V1::UsersController PUT/PATCH #update when is successfully updated renders the json representation for the updated user
     Failure/Error: if user.update(user_params)

     NoMethodError:
       undefined method 'update' for nil:NilClass
   ...
....

La solution est assez simple, il suffit d’ajouter l’en-tête `Authorization` à la requête:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  # ...
  describe 'PUT/PATCH #update' do
    context 'when is successfully updated' do
      before(:each) do
        @user = FactoryBot.create :user
        request.headers['Authorization'] = @user.auth_token
        patch :update, params: { id: @user.id, user: { email: 'newmail@example.com' } }, format: :json
      end
      # ...
    end

    context 'when is not created' do
      before(:each) do
        @user = FactoryBot.create :user
        request.headers['Authorization'] = @user.auth_token
        patch :update, params: { id: @user.id, user: { email: 'bademail.com' } }, format: :json
      end
      # ...
    end
  end
  # ...
end
----

Maintenant, les tests devraient passer. Mais attendez, quelque chose ne va pas, n’est-ce pas? Nous pouvons factoriser la ligne que nous venons d’ajouter et la mettre dans le module `HeadersHelpers`:

[source,ruby]
.spec/support/request_helpers.rb
----
module Request
  # ...
  module HeadersHelpers
    # ...
    def api_authorization_header(token)
      request.headers['Authorization'] = token
    end
  end
end
----

Maintenant, chaque fois que nous avons besoin d’avoir l’utilisateur courant sur nos tests, nous appelons simplement la méthode `api_authorization_header`. Je vous laisse le faire avec `users_controller_spec.rb` pour le test de mise à jour ?:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  # ...
  describe 'PUT/PATCH #update' do
    context 'when is successfully updated' do
      before(:each) do
        @user = FactoryBot.create :user
        api_authorization_header @user.auth_token
        patch :update, params: { id: @user.id, user: { email: 'newmail@example.com' } }, format: :json
      end
      # ...
    end

    context 'when is not created' do
      before(:each) do
        @user = FactoryBot.create :user
        api_authorization_header @user.auth_token
        patch :update, params: { id: @user.id, user: { email: 'bademail.com' } }, format: :json
      end
      # ...
    end
  end
  # ...
end
----

Pour l’action `destroy`, nous ferons la même chose car nous devons juste nous assurer qu’un utilisateur est capable de se supprimer:

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  # ...
  def destroy
    current_user.destroy
    head 204
  end
  # ...
end
----

Maintenant, pour le fichier de spécification, et comme mentionné précédemment, nous avons juste besoin d’ajouter l’en-tête `api_authorization_header`:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  # ...
  describe 'DELETE #destroy' do
    before(:each) do
      @user = FactoryBot.create :user
      api_authorization_header @user.auth_token
      delete :destroy, params: { id: @user.id }
    end

    it { expect(response.response_code).to eq(204) }
  end
end
----

Tous nos tests devraient passer. La dernière étape de cette section consiste à ajouter les droits d’accès correspondants pour ces deux dernières actions.

Il est courant de simplement empêcher les actions sur lesquelles l’utilisateur effectue des actions sur le modèle lui-même. Dans ce cas l’action `update` et `destroy`.

Sur le `users_controller.rb` nous devons filtrer certaines de ces actions pour empêcher l’accès.

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  before_action :authenticate_with_token!, only: %i[update destroy]
  respond_to :json
  # ...
end
----

Nos tests devraient être encore bons. Et à partir de maintenant, chaque fois que nous voulons éviter qu’une action ne soit déclenchée, nous ajoutons simplement la méthode `authenticate_with_token!` sur un _hook_ `before_action`.

_Commitons_ tout ça:

[source,bash]
----
$ git add .
$ git commit -m "Adds authorization for the users controller"
----

Enfin, nous terminerons le chapitre en remaniant la méthode `authenticate_with_token!`, C’est une petite amélioration mais cela rendra la méthode plus parlante. Vous comprendrez ce que je veux dire dans une minute, mais avant tout, ajoutons quelques tests.

[source,ruby]
.spec/controllers/concerns/authenticable_spec.rb
----
# ...
RSpec.describe Authenticable do
  # ...
  describe '#user_signed_in?' do
    context "when there is a user on 'session'" do
      before do
        @user = FactoryBot.create :user
        authentication.stub(:current_user).and_return(@user)
      end

      it { should be_user_signed_in }
    end

    context "when there is no user on 'session'" do
      before do
        @user = FactoryBot.create :user
        authentication.stub(:current_user).and_return(nil)
      end

      it { should_not be_user_signed_in }
    end
  end
end
----

Comme vous pouvez le voir, nous avons ajouté deux simples tests pour savoir si l’utilisateur est connecté ou non. Et comme je l’ai déjà dit, c’est juste pour la clarté visuelle. Mais continuons et ajoutons l’implémentation:

[source,ruby]
.app/controllers/concerns/authenticable.rb
----
module Authenticable
  # ...
  def authenticate_with_token!
    unless user_signed_in?
      render json: { errors: 'Not authenticated' }, status: :unauthorized
    end
  end

  def user_signed_in?
    current_user.present?
  end
end
----

Comme vous pouvez le voir, maintenant `authenticate_with_token!` est plus facile à lire non seulement pour vous mais aussi pour les autres développeurs qui rejoigneront le projet. Cette approche a également un avantage secondaire: si vous voulez modifier ou améliorer la façon de valider, vous pouvez simplement le faire sur la méthode `user_signed_in?`.

Maintenant, nos tests devraient être tous verts:

[source,bash]
----
$ rspec spec/controllers/concerns/authenticable_spec.rb
.....

Finished in 0.07415 seconds (files took 0.702 seconds to load)
5 examples, 0 failures
----

_Commitons_ tout ça:

[source,bash]
----
$ git add .
$ git commit -m "Adds user_signed_in? method to know whether the user is logged in or not"
----

== Conclusion

Vous l’avez fait! Vous êtes à mi-chemin! Ce chapitre a été long et difficile, mais c’est un grand pas en avant sur la mise en place d’un mécanisme solide pour gérer l’authentification utilisateur et nous grattons même la surface pour de simples règles d’autorisation.

Dans le prochain chapitre, nous nous concentrerons sur la personnalisation de la sortie JSON pour l’utilisateur avec `active_model_serializers` et l’ajout d’un modèle de produit en donnant à l’utilisateur la possibilité de créer un produit et le publier pour la vente.
