[#chapter10-optimization]
= Optimizations

Welcome to the last chapter of the book. It's been a long way and you are only one step away from the end. Back in previous chapter we finish modeling the `Order` model and we could say that the project is done by now, but I want to cover some important details about optimization. The topics I'm going to cover in here will be:

* Setup more https://jsonapi.org/[JSON:API] specifications
* Pagination
* Caching

I will try to go as deep as I can trying to cover some common scenarios on this, and hopefully by the end of the chapter you'll have enough knowledge to apply into some other scenarios.

If you start reading at this point, you'll probably want the code to work on, you can clone it like so:

[source,bash]
----
$ git clone https://github.com/madeindjs/market_place_api.git -b chapter9
----

Let's now create a branch to start working:

[source,bash]
----
$ git checkout -b chapter10
----

== Setup more https://jsonapi.org/[JSON:API] specifications

As I have been telling you since the beginning of this book, an important and difficult part of creating your API is deciding the output format. Fortunately, some organizations have already faced this type of problem and have established certain conventions.

One of the most applied conventions is most certainly https://jsonapi.org/[JSON:API]. This convention will allow us to approach pagination more serenely in the next section.

So https://jsonapi.org/format/#document-structure[documentation JSON:API] gives us some rules to follow concerning JSON presentation.

So our *document* must follow theses rules:

* `data`: which must contains the data we send back
* `errors` which must contains a table of errors that have occurred
* `meta` which contains https://jsonapi.org/format/#document-meta[object meta]

NOTE: The `data` and `errors` keys must not be present at the same time and this makes sense since if an error occurs we should not be able to make data correct.

The content of the `data` key is also quite strict:

* it must have a `type` key that describes the type of the JSON model (if it is an article, a user, etc.)
* the properties of the objects must be placed in an `attributes` key and the underscore (`_`) are replaced by dashes (`-`)
* the links of the objects must be placed in a `relationships` key

This may cause us a lot of change since we have not implemented any of its rules. Don't worry, we have set up unit tests to ensure that there will be no regression. Let's start with doc updating them

=== Users

So let's start with users controller. Take a look at `show` action:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  describe 'GET #show' do
    # ...
    it 'returns the information about a reporter on a hash' do
      expect(json_response[:email]).to eql @user.email
    end

    it 'has the product ids as an embedded object' do
      expect(json_response[:product_ids]).to eql []
    end
  end
  # ...
end
----

We just need to update emplacement of data. So the complete update file look like this:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  describe 'GET #show' do
    # ...
    it 'returns the information about a reporter on a hash' do
      expect(json_response[:data][:attributes][:email]).to eql @user.email
    end

    it 'has the product ids as an embedded object' do
      expect(json_response[:data][:attributes][:'product-ids']).to eql []
    end
  end

  describe 'POST #create' do
    context 'when is successfully created' do
      # ...
      it 'renders the json representation for the user record just created' do
        expect(json_response[:data][:attributes][:email]).to eql @user_attributes[:email]
      end
    end
    # ...
  end

  describe 'PUT/PATCH #update' do
    context 'when is successfully updated' do
      # ...
      it 'renders the json representation for the updated user' do
        expect(json_response[:data][:attributes][:email]).to eql 'newmail@example.com'
      end
    end
    # ...
  end
  # ...
end
----

And that's it. It display a lot of code but there are few changes.

=== User's sessions

Only one test should be updated for user's sessions: the one who get `auth_token`.

[source,ruby]
.spec/controllers/api/v1/sessions_controller_spec.rb
----
# ...
RSpec.describe Api::V1::SessionsController, type: :controller do
  describe 'POST #create' do
    # ...
    context 'when the credentials are correct' do
      # ...
      it 'returns the user record corresponding to the given credentials' do
        @user.reload
        expect(json_response[:data][:attributes][:'auth-token']).to eql @user.auth_token
      end
      # ...
    end
  # ...
  end
end
----

NOTE: Remember that JSON:API specifications use dashes (`-`) instead of underscore (`_`)

=== Orders

There are one specificity for orders controller: we also get linked user. So to do so we need to use the `:relationships`. Apart from that, the principle remains the same:

[source,ruby]
.spec/controllers/api/v1/products_controller_spec.rb
----
# ...
RSpec.describe Api::V1::ProductsController, type: :controller do
  describe 'GET #show' do
    # ...
    it 'returns the information about a reporter on a hash' do
      expect(json_response[:data][:attributes][:title]).to eql @product.title
    end

    it 'has the user as a embedded object' do
      puts json_response.inspect
      expect(json_response[:data][:relationships][:user][:attributes][:email]).to eql @product.user.email
    end
    # ...
  end

  describe 'GET #index' do
    # ...
    context 'when is not receiving any product_ids parameter' do
      # ...
      it 'returns 4 records from the database' do
        expect(json_response[:data]).to have(4).items
      end
      it 'returns the user object into each product' do
        json_response.each do |product_response|
          expect(product_response[:data][:relationships][:user]).to be_present
        end
      end
      # ...
    end

    context 'when product_ids parameter is sent' do
      # ...
      it 'returns just the products that belong to the user' do
        json_response.each do |product_response|
          expect(product_response[:data][:relationships][:user][:attributes][:email]).to eql @user.email
        end
      end
    end
  end

  describe 'POST #create' do
    context 'when is successfully created' do
      # ...
      it 'renders the json representation for the product record just created' do
        expect(json_response[:data][:attributes][:title]).to eql @product_attributes[:title]
      end
      # ...
    end
    # ...
  end

  describe 'PUT/PATCH #update' do
    # ...
    context 'when is successfully updated' do
      # ...
      it 'renders the json representation for the updated user' do
        expect(json_response[:data][:attributes][:title]).to eql 'An expensive TV'
      end
      # ...
    end
    # ...
  end
  # ...
end
----

==== Product

Again, that's a lot of code, but in reality there's very little change.

[source,ruby]
.spec/controllers/api/v1/products_controller_spec.rb
----
# ...
RSpec.describe Api::V1::ProductsController, type: :controller do
  describe 'GET #show' do
    # ...

    it 'returns the information about a reporter on a hash' do
      expect(json_response[:data][:attributes][:title]).to eql @product.title
    end

    it 'has the user as a embedded object' do
      expect(json_response[:data][:relationships][:user][:attributes][:email]).to eql @product.user.email
    end
  end

  describe 'GET #index' do
    # ...
    context 'when is not receiving any product_ids parameter' do
      # ...
      it 'returns 4 records from the database' do
        expect(json_response[:data]).to have(4).items
      end

      it 'returns the user object into each product' do
        json_response.each do |product_response|
          expect(product_response[:data][:relationships][:user]).to be_present
        end
      end
    end

    context 'when product_ids parameter is sent' do
      # ...
      it 'returns just the products that belong to the user' do
        json_response.each do |product_response|
          expect(product_response[:data][:relationships][:user][:attributes][:email]).to eql @user.email
        end
      end
    end
  end

  describe 'POST #create' do
    context 'when is successfully created' do
      # ...
      it 'renders the json representation for the product record just created' do
        product_response = json_response
        expect(product_response[:data][:attributes][:title]).to eql @product_attributes[:title]
      end
      # ...
    end

    context 'when is not created' do
      # ...
      it 'renders the json errors on why the user could not be created' do
        product_response = json_response
        expect(product_response[:errors][:price]).to include 'is not a number'
      end
      # ...
    end
  end

  describe 'PUT/PATCH #update' do
    # ...
    context 'when is successfully updated' do
      # ...
      it 'renders the json representation for the updated user' do
        expect(json_response[:data][:attributes][:title]).to eql 'An expensive TV'
      end
      # ...
    end
    # ...
  end
  # ...
end
----

=== Implementation

From the beginning, in order to serialize our models, we used _Active Model Serializer_. Fortunately for us this library offers several *adapters*. The adapters are in a way JSON models to be applied to all our serializers. It's perfect.

The https://github.com/rails-api/active_model_serializers/blob/v0.10.6/docs/general/adapters.md[documentation of _Active Model Serializer_] shows us a list of existing adapters. And if you see where I'm going with this there's one ready for the JSON:API model! To set it up, simply activate the adapt it by creating the following file:

[source,ruby]
.config/initializers/activemodel_serializer.rb
----
ActiveModelSerializers.config.adapter = :json_api
----

We must also indicate the type of the serializer object. _Active Model Serializer_ offers an all fate method for this: `type`. Implementation is therefore very easy:


[source,ruby]
.app/serializers/order_serializer.rb
----
class OrderSerializer < ActiveModel::Serializer
  type :order
  # ...
end
----

[source,ruby]
.app/serializers/product_serializer.rb
----
class ProductSerializer < ActiveModel::Serializer
  type :product
  # ...
end
----

[source,ruby]
.app/serializers/user_serializer.rb
----
class UserSerializer < ActiveModel::Serializer
  type :user
  # ...
end
----

And that's all! Now let's run *all* our tests to see if they pass:

[source,bash]
----
$ rspec spec
...........F.F.F.......................................................................................

Failures:

  1) Api::V1::ProductsController GET #show has the user as a embedded object
     Failure/Error: expect(json_response[:data][:relationships][:user][:attributes][:email]).to eql @product.user.email
     ...

  2) Api::V1::ProductsController GET #index when is not receiving any product_ids parameter returns the user object into each product
     Failure/Error: expect(product_response[:data][:relationships][:user]).to be_present
     ...

  3) Api::V1::ProductsController GET #index when product_ids parameter is sent returns just the products that belong to the user
     Failure/Error: expect(product_response[:data][:relationships][:user][:attributes][:email]).to eql @user.email
     ...

Finished in 1.35 seconds (files took 1.1 seconds to load)
103 examples, 3 failures
----

Argh…. All our tests pass but we see that the user associated with the product is not integrated in the answer. This is actually quite normal. The JSON:API https://jsonapi.org/format/#fetching-includes[documentation] recommends using an `include` key rather than nesting models together.

So let's update our test:

[source,ruby]
.spec/controllers/api/v1/products_controller_spec.rb
----
# ...
RSpec.describe Api::V1::ProductsController, type: :controller do
  describe 'GET #show' do
    # ...
    it 'has the user as a embedded object' do
      expect(json_response[:included].first[:attributes][:email]).to eql @product.user.email
    end
  end

  describe 'GET #index' do
    # ...
    context 'when is not receiving any product_ids parameter' do
      # ...
      it 'returns the user object into each product' do
        expect(json_response[:included]).to be_present
      end
      # ...
    end

    context 'when product_ids parameter is sent' do
      # ...
      it 'returns just the products that belong to the user' do
        expect(json_response[:included].first[:id].to_i).to eql @user.id
      end
    end
  end
  # ...
end
----

Here too implementation is very easy. We just need to add the `include` option directly into the controller's action.

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  #...
  def index
    render json: Product.search(params), include: [:user]
  end

  def show
    render json: Product.find(params[:id]), include: [:user]
  end
  #...
end
----

Let's run all the tests again to make sure that our final implementation is correct:

[source,bash]
----
$ rspec spec
.......................................................................................................

Finished in 2.12 seconds (files took 1.4 seconds to load)
103 examples, 0 failures
----

And that's the job. Since we are happy with our work, let's do a commit:

[source,bash]
----
$ git add .
$ git commit -m "Respect JSON:API response format"
----

== Pagination

A very common strategy to optimize an array of records from the database, is to load just a few by paginating them and if you are familiar with this technique you know that in Rails is really easy to achieve it whether if you are using https://github.com/mislav/will_paginate[will_paginate] or https://github.com/amatsuda/kaminari[kaminari].

Then only tricky part in here is how are we suppose to handle the JSON output now, to give enough information to the client on how the array is paginated. If you recall first chapter I shared some resources on the practices I was going to be following in here. One of them was http://jsonapi.org/ which is a must-bookmark page.

If we read the format section we will reach a sub section called http://jsonapi.org/format/#document-structure-top-level[Top Level] and in very few words they mention something about pagination:

> "meta": meta-information about a resource, such as pagination.

It is not very descriptive but at least we have a hint on what to look next about the pagination implementation, but don't worry that is exactly what we are going to do in here.

Let's start with the `products` list.

=== Products

We are going to start nice and easy by paginating the products list as we don't have any kind of access restriction which leads to easier testing.

First we need to add the https://github.com/amatsuda/kaminari[kaminari] gem to our `Gemfile`:

[source,bash]
----
$ bundle add kaminari
----

Now we can go to the `index` action on the `products_controller` and add the pagination methods as pointed on the documentation:

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  # ...
  def index
    render json: Product.page(params[:page]).per(params[:per_page]).search(params)
  end
  # ...
end
----

So far the only thing that changed is the query on the database to just limit the result by 25 per page which is the default. But we have not added any extra information to the JSON output.

We need to provide the pagination information on the `meta` tag in the following form:

[source,json]
----
"meta": {
    "pagination": {
        "per_page": 25,
        "total_page": 6,
        "total_objects": 11
    }
}
----

Now that we have the final structure for the `meta` tag we just need to output it on the JSON response. Let's first add some specs:

[source,ruby]
.spec/controllers/api/v1/products_controller_spec.rb
----
# ...
RSpec.describe Api::V1::ProductsController, type: :controller do
  # ...
  describe 'GET #index' do
    before(:each) do
      4.times { FactoryBot.create :product }
      get :index
    end
    # ...
    it 'Have a meta pagination tag' do
      expect(json_response).to have_key(:meta)
      expect(json_response[:meta]).to have_key(:pagination)
      expect(json_response[:meta][:pagination]).to have_key(:'per-page')
      expect(json_response[:meta][:pagination]).to have_key(:'total-pages')
      expect(json_response[:meta][:pagination]).to have_key(:'total-objects')
    end

    it { expect(response.response_code).to eq(200) }
  end
  # ...
end
----

The test we have just added should fail or, if we run the tests, two tests fail. It means we broke something else:

[source,bash]
----
$ bundle exec rspec spec/controllers/api/v1/products_controller_spec.rb
...F....F...........

Failures:

  1) Api::V1::ProductsController GET #index Have a meta pagination tag
     ...

  2) Api::V1::ProductsController GET #index when product_ids parameter is sent returns just the products that belong to the user
     Failure/Error: total_pages: products.total_pages,

     NoMethodError:
       undefined method 'total_pages' for #<Array:0x0000556f1ef85c68>
     # ./app/controllers/api/v1/products_controller.rb:12:in 'index'
     ...

Finished in 0.40801 seconds (files took 0.62979 seconds to load)
20 examples, 2 failures
----

The error is actually on the `Product.search` method. In fact Kaminari is waiting for a registration relationship instead of a table. It's very easy to repair:

[source,ruby]
.app/models/product.rb
----
class Product < ApplicationRecord
  # ...
  def self.search(params = {})
    products = params[:product_ids].present? ? Product.where(id: params[:product_ids]) : Product.all
    # ...
  end
end
----

Have you noticed the change? Let me explain it to you. We simply replaced the `Product.find` method with `Product.where` using the `product_ids` parameters. The difference is that the `where` method returns an `ActiveRecord::Relation` and that's exactly what we need.

Now, if we restart the tests, the test we broke should now pass:

[source,bash]
----
$ bundle exec rspec spec/controllers/api/v1/products_controller_spec.rb
...F................

Failures:

  1) Api::V1::ProductsController GET #index Have a meta pagination tag
     ...

Finished in 0.41533 seconds (files took 0.5997 seconds to load)
20 examples, 1 failure
----

Now that we fixed that, let's add the pagination information, we need to do it on the `products_controller.rb` file:

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  before_action :authenticate_with_token!, only: %i[create update destroy]

  def index
    products = Product.search(params).page(params[:page]).per(params[:per_page])
    render(
      json: products,
      include: [:user],
      meta: {
        pagination: {
          per_page: params[:per_page],
          total_pages: products.total_pages,
          total_objects: products.total_count
        }
      }
    )
  end
  # ...
end
----

Now if we run the specs, they should be all passing:

[source,bash]
----
$ bundle exec rspec spec/controllers/api/v1/products_controller_spec.rb
....................

Finished in 0.66813 seconds (files took 2.72 seconds to load)
20 examples, 0 failures
----

Now we have make a really amazing optimization for the products list endpoint. Now it is the client job to fetch the correct `page` with the correct `per_page` param for the records.

Let's commit this changes and proceed with the orders list.

[source,bash]
----
$ git add .
$ git commit -m "Adds pagination for the products index action to optimize response"
----

=== Orders list

Now it's time to do exactly the same for the `orders` list endpoint which should be really easy to implement. But first, let's add some specs to the `orders_controller_spec.rb` file:

[source,ruby]
.spec/controllers/api/v1/orders_controller_spec.rb
----
# ...
RSpec.describe Api::V1::OrdersController, type: :controller do
  describe 'GET #index' do
    before(:each) do
      current_user = FactoryBot.create :user
      api_authorization_header current_user.auth_token
      4.times { FactoryBot.create :order, user: current_user }
      get :index, params: { user_id: current_user.id }
    end

    it 'returns 4 order records from the user' do
      expect(json_response[:data]).to have(4).items
    end

    it 'Have a meta pagination tag' do
      expect(json_response).to have_key(:meta)
      expect(json_response[:meta]).to have_key(:pagination)
      expect(json_response[:meta][:pagination]).to have_key(:'per-page')
      expect(json_response[:meta][:pagination]).to have_key(:'total-pages')
      expect(json_response[:meta][:pagination]).to have_key(:'total-objects')
    end

    it { expect(response.response_code).to eq(200) }
  end
  # ...
end
----

As you may already know, our tests are no longer passing:

[source,bash]
----
$ rspec spec/controllers/api/v1/orders_controller_spec.rb
.F........

Failures:

  1) Api::V1::OrdersController GET #index Have a meta pagination tag
     Failure/Error: expect(json_response).to have_key(:meta)
       expected #has_key?(:meta) to return true, got false
     # ./spec/controllers/api/v1/orders_controller_spec.rb:18:in `block (3 levels) in <top (required)>'

Finished in 0.66262 seconds (files took 2.74 seconds to load)
10 examples, 1 failure
----

Let's turn the red into green:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  before_action :authenticate_with_token!

  def index
    orders = current_user.orders.page(params[:page]).per(params[:per_page])
    render(
      json: orders,
      meta: {
        pagination: {
          per_page: params[:per_page],
          total_pages: orders.total_pages,
          total_objects: orders.total_count
        }
      }
    )
  end
  # ...
end
----

Now all the tests should be nice and green:

[source,bash]
----
$ rspec spec/controllers/api/v1/orders_controller_spec.rb
..........

Finished in 0.35201 seconds (files took 0.9404 seconds to load)
10 examples, 0 failures
----

Let's place and commit, because a refactor is coming:

[source,bash]
----
$ git commit -am "Adds pagination for orders index action"
----

=== Refactoring pagination

If you have followed this tutorial or if you are an experienced Rails developer, you probably like to keep things DRY. You may have noticed that the code we just wrote is duplicated. I think it's a good habit to clean up the code a little once the functionality is implemented.

We will first clean up these tests that we duplicated in the file `orders_controller_spec.rb` and `products_controller_spec.rb`:

[source,ruby]
----
it 'Have a meta pagination tag' do
  expect(json_response).to have_key(:meta)
  expect(json_response[:meta]).to have_key(:pagination)
  expect(json_response[:meta][:pagination]).to have_key(:'per-page')
  expect(json_response[:meta][:pagination]).to have_key(:'total-pages')
  expect(json_response[:meta][:pagination]).to have_key(:'total-objects')
end
----

Let's add a `shared_examples` folder under the `spec/support/` directory:

[source,bash]
----
$ mkdir spec/support/shared_examples
----

And on the `pagination.rb` file you can just add the following lines:

[source,ruby]
.spec/support/shared_examples/pagination.rb
----
shared_examples 'paginated list' do
  it 'Have a meta pagination tag' do
    expect(json_response).to have_key(:meta)
    expect(json_response[:meta]).to have_key(:pagination)
    expect(json_response[:meta][:pagination]).to have_key(:'per-page')
    expect(json_response[:meta][:pagination]).to have_key(:'total-pages')
    expect(json_response[:meta][:pagination]).to have_key(:'total-objects')
  end
end
----

This shared example can now be use as a substitute for the five tests on the `orders_controller_spec.rb` and `products_controller_spec.rb` files like so:

[source,ruby]
.spec/controllers/api/v1/orders_controller_spec.rb
----
# ...
RSpec.describe Api::V1::OrdersController, type: :controller do
  describe 'GET #index' do
    # ...
    it_behaves_like 'paginated list'
    # ...
  end
end
----

[source,ruby]
.spec/controllers/api/v1/products_controller_spec.rb
----
# ...
RSpec.describe Api::V1::ProductsController, type: :controller do
  # ...
  describe 'GET #index' do
    # ...
    it_behaves_like 'paginated list'
    # ...
  end
  # ...
end
----

And both specs should be passing.

[source,bash]
----
$ rspec spec/controllers/api/v1/
.................................................

Finished in 0.96778 seconds (files took 1.59 seconds to load)
49 examples, 0 failures
----

Now that we made this simple refactor we can jump into the pagination implementation for the controllers and clean things up. If you recall the index action for both the products and orders controller they both have the same pagination format. So let's move this logic into a method called `pagination` under the `application_controller.rb` file. This way we can access it on any controller which needs pagination in the future.

[source,ruby]
.app/controllers/application_controller.rb
----
class ApplicationController < ActionController::API
  include Authenticable

  # @return [Hash]
  def pagination(paginated_array)
    {
      pagination: {
        per_page: params[:per_page],
        total_pages: paginated_array.total_pages,
        total_objects: paginated_array.total_count
      }
    }
  end
end
----

And now we can substitute the pagination hash on both controllers for the method, like so:

[source,ruby]
.app/controllers/api/v1/orders_controller.rb
----
class Api::V1::OrdersController < ApplicationController
  # ...
  def index
    orders = current_user.orders.page(params[:page]).per(params[:per_page])
    render(
      json: orders,
      meta: pagination(orders)
    )
  end
  # ...
end
----

[source,ruby]
.app/controllers/api/v1/products_controller.rb
----
class Api::V1::ProductsController < ApplicationController
  # ...
  def index
    products = Product.search(params).page(params[:page]).per(params[:per_page])
    render(
      json: products,
      include: [:user],
      meta: pagination(products)
    )
  end
  # ...
end
----

If you run the specs for each file they should be all nice and green:

[source,bash]
----
$ rspec spec/controllers/api/v1/
.................................................

Finished in 0.92996 seconds (files took 0.95615 seconds to load)
49 examples, 0 failures
----

This would be a good time to commit the changes and move on to the next section on caching.

[source,bash]
----
$ git add .
----

== API Caching

There is currently an implementation to do caching with the gem `active_model_serializers` which is really easy to handle. Although in older versions of the gem, this implementation can change, it does the job.

If we make a request to the product list, we will notice that the response time takes about 174 milliseconds using cURL

[source,bash]
----
$ curl -w 'Total: %{time_total}\n' -o /dev/null -s http://api.marketplace.dev/products
Total: 0,174111
----

NOTE: The `-w` option allows us to retrieve the time of the request, `-o` redirects the response to a file and `-s` hides the cURL display

By adding only one line to the `ProductSerializer` class, we will see a significant improvement in response time!

[source,ruby]
.app/serializers/product_serializer.rb
----
class ProductSerializer < ActiveModel::Serializer
  # ...
  cache key: 'product', expires_in: 3.hours
end
----

[source,ruby]
.app/serializers/order_serializer.rb
----
class OrderSerializer < ActiveModel::Serializer
  # ...
  cache key: 'order', expires_in: 3.hours
end
----

[source,ruby]
.app/serializers/user_serializer.rb
----
class UserSerializer < ActiveModel::Serializer
  # ...
  cache key: 'user', expires_in: 3.hours
end
----

And that's all! Let's check for improvement:

[source,bash]
----
$ curl -w 'Total: %{time_total}\n' -o /dev/null -s http://api.marketplace.dev/products
Total: 0,021599
$ curl -w 'Total: %{time_total}\n' -o /dev/null -s http://api.marketplace.dev/products
Total: 0,021979
----

So we went from 174 ms to 21 ms. The improvement is therefore enormous! Let's commit our change a last time:

[source,ruby]
----
$ git commit -am "Adds caching for the serializers"
----

== Conclusion

If you get to that point, it means you're done with the book. Good work! You have just become a great API Rails developer, that's for sure.

Thank you for bringing this great adventure with me, I hope you enjoyed the trip as much as I did. We should have a beer sometime.
