[#chapter05-authentication]
= Authenticating users

It's been a long way since you started. I hope you are enjoying this trip as much as me. On previous chapter we refactor our test suite and since we did not add much code. If you skipped that chapter I recommend you read it. As we are going to be using some of the methods in the chapters to come.

You can clone the project up to this point:

[source,bash]
----
$ git clone --branch chapitre_4 https://github.com/madeindjs/market_place_api
----

In this chapter things will get very interesting because we are going to set up our authentication mechanism. In my opinion this is going to be one of the most interesting chapters. We will introduce a lot of new terms and you will end with a simple but powerful authentication system. Don't feel panic we will get to that.

First things first (and as usual when starting a new chapter) we will create a new branch:

[source,bash]
----
$ git checkout -b chapter5
----

== Stateless session

Before we go any further, something must be clear: *an API does not handle sessions*. If you don't have experience building these kind of applications it might sound a little crazy but stay with me. An API should be stateless which means by definition _is one that provides a response after your request, and then requires no further attention._. Which means no previous or future state is required for the system to work.

The flow for authenticating the user through an API is very simple:

[arabic]
. The client request for `sessions` resource with the corresponding credentials, usually email and password.
. The server returns the `user` resource along with its corresponding authentication token
. Every page that requires authentication, the client has to send that `authentication token`

Of course this is not the only 3-step to follow, and even on step 2 you might think, well do I really need to respond with the entire user or just the `authentication token`, I would say, it really depends on you, but I like to return the entire user, this way I can map it right away on my client and save another possible request from being placed.

In this section and the next we will be focusing on building a Sessions controller along with its corresponding actions. We'll then complete the request flow by adding the necessary authorization access.

== Authentication token

Before we proceed with the logic on the sessions controller, we have to first add the `authentication token` field to the `user` model and then add a method to actually set it.

First we generate the migration file:

[source,bash]
----
$ rails generate migration add_authentification_token_to_users auth_token:string
----

As a good practice I like to setup `string` values to an empty string. Let's add an index with a unique truly condition. This way we warranty there are no users with the same token at a database level. So let's do that:

[source,ruby]
.db/migrate/20181114134521_add_authentification_token_to_users.rb
----
class AddauthentificationTokenToUsers < ActiveRecord::Migration[5.2]
  def change
    add_column :users, :auth_token, :string, default: ''
    add_index :users, :auth_token, unique: true
  end
end
----

Then we run the migrations to add the field and prepare the test database:

[source,bash]
----
$ rake db:migrate
== 20181114134521 AddauthentificationTokenToUsers: migrating ====================
-- add_column(:users, :auth_token, :string, {:default=>""})
   -> 0.0004s
-- add_index(:users, :auth_token, {:unique=>true})
   -> 0.0010s
== 20181114134521 AddauthentificationTokenToUsers: migrated (0.0016s) ===========
----

Now it would be a good time to add some response and uniqueness tests to our `user` model spec:

[source,ruby]
.spec/models/user_spec.rb
----
RSpec.describe User, type: :model do
  # ...
  it { should respond_to(:auth_token) }
  it { should validate_uniqueness_of(:auth_token)}
end
----

We then move to the `user.rb` file and add the necessary code to make our tests pass:

[source,ruby]
/app/models/user.rb
----
class User < ApplicationRecord
  validates :auth_token, uniqueness: true
  # ...
end
----

Next we will work on a method that will generate a unique authentication token for each user in order to authenticate them later through the API. So let's build the tests first.

[source,ruby]
.spec/models/user_spec.rb
----
RSpec.describe User, type: :model do
  # ...
  describe "#generate_authentification_token!" do
    it "generates a unique token" do
      @user.generate_authentification_token!
      expect(@user.auth_token).not_to be_nil
    end

    it "generates another token when one already has been taken" do
      existing_user = FactoryBot.create(:user, auth_token: "auniquetoken123")
      @user.generate_authentification_token!
      expect(@user.auth_token).not_to eql existing_user.auth_token
    end
  end
end
----

Before use `validate_uniqueness_of` method we have to install `shoulda-matchers` gem. To do so add this gem in `Gemfile`:

[source,ruby]
.Gemfile
----
# ...
group :test do
  # ...
  gem 'shoulda-matchers'
end
----

And load it in `rails_helper.rb`:

[source,ruby]
.spec/rails_helper.rb
----
# ...
RSpec.configure do |config|
  # ...
  RSpec.configure do |config|
    config.include(Shoulda::Matchers::ActiveModel, type: :model)
    config.include(Shoulda::Matchers::ActiveRecord, type: :model)
  end
end
----

The tests initially fail, as expected:

....
$ bundle exec rspec spec/models/user_spec.rb
.......FF

Failures:

  1) User#generate_authentification_token! generates a unique token
     Failure/Error: @user.generate_authentification_token!

     NoMethodError:
       undefined method `generate_authentification_token!' for #<User:0x0000558948d23760>
     # ./spec/models/user_spec.rb:23:in `block (3 levels) in <top (required)>'

  2) User#generate_authentification_token! generates another token when one already has been taken
     Failure/Error: @user.generate_authentification_token!

     NoMethodError:
       undefined method `generate_authentification_token!' for #<User:0x0000558948d18720>
     # ./spec/models/user_spec.rb:29:in `block (3 levels) in <top (required)>'
....

We are going to hook this `generate_authentication_token!` to a `before_create` callback to warranty every user has an authentication token which does not collides with an existing one. To create the token there are many solutions, I'll go with the `friendly_token` that devise offers already, but I could also do it with the `hex` method from the https://ruby-doc.org/stdlib-2.5.3/libdoc/securerandom/rdoc/SecureRandom.html[`SecureRandom`] class.

The code to generate the token is fairly simple:

[source,ruby]
.app/models/user.rb
----
class User < ApplicationRecord
  before_create :generate_authentification_token!
  # ...
  def generate_authentification_token!
    begin
      self.auth_token = Devise.friendly_token
    end while self.class.exists?(auth_token: auth_token)
  end
end
----

After that we just need to hook it up to the `before_create` callback:

[source,bash]
----
$ bundle exec rspec spec/models/user_spec.rb
.........

Finished in 0.05079 seconds (files took 0.49029 seconds to load)
9 examples, 0 failures
----

As usual, let's commit the changes and move on:

[source,bash]
----
$ git add .
$ git commit -m "Adds user authentification token"
----

== Sessions controller

Back to the sessions controller the `actions` we'll be implementing on it are going to be handled as RESTful services: the sign in will be handled by a _POST_ request to the `create` action and the sign out will be handled by a _DELETE_ request to the `destroy` action.

To get started we will start by creating the sessions controller:

[source,bash]
----
$ rails generate controller sessions
----

Then we need to move the files into the `api/v1` directory, for both on the `app` and `spec` folders:

[source,bash]
----
$ mv app/controllers/sessions_controller.rb app/controllers/api/v1
$ mv spec/controllers/sessions_controller_spec.rb spec/controllers/api/v1
----

After moving the files we have to update them to meet the directory structure we currently have as shown on followed snippets:

[source,ruby]
.app/controllers/api/v1/sessions_controller.rb
----
class Api::V1::SessionsController < ApplicationController
end
----

[source,ruby]
.spec/controllers/api/v1/sessions_controller_spec.rb
----
# ...
RSpec.describe Api::V1::SessionsController, type: :controller do
end
----

=== Sign in success

Our first stop will be the `create` action. But first let's generate our tests:

[source,ruby]
.spec/controllers/api/v1/sessions_controller_spec.rb
----
# ...
RSpec.describe Api::V1::SessionsController, type: :controller do
  describe 'POST #create' do
    before(:each) do
      @user = FactoryBot.create :user
    end

    context 'when the credentials are correct' do
      before(:each) do
        post :create, params: {
          session: { email: @user.email, password: '12345678' }
        }
      end

      it 'returns the user record corresponding to the given credentials' do
        @user.reload
        expect(json_response[:auth_token]).to eql @user.auth_token
      end

      it { expect(response.response_code).to eq(200) }
    end

    context 'when the credentials are incorrect' do
      before(:each) do
        post :create, params: {
          session: { email: @user.email, password: 'invalidpassword' }
        }
      end

      it 'returns a json with an error' do
        expect(json_response[:errors]).to eql 'Invalid email or password'
      end

      it { expect(response.response_code).to eq(422) }
    end
  end
end
----

The tests are pretty straightforward. We simply return the `user` in JSON format if the credentials are correct but if not we just send a JSON with an error message. Next we need to implement the code to make our tests be green. But before that we will add the end points to our `route.rb` file (both the `create` and `destroy` end point).

[source,ruby]
.config/routes.rb
----
# ...
Rails.application.routes.draw do
  # ...
  resources :sessions, :only => [:create, :destroy]
end
----

[source,ruby]
.app/controllers/api/v1/sessions_controller.rb
----
class Api::V1::SessionsController < ApplicationController
  def create
    user_password = params[:session][:password]
    user_email = params[:session][:email]
    user = user_email.present? && User.find_by(email: user_email)

    if user.valid_password? user_password
      sign_in user
      user.generate_authentification_token!
      user.save
      render json: user, status: 200, location: [:api, user]
    else
      render json: { errors: 'Invalid email or password' }, status: 422
    end
  end
end
----

Before we run our tests it is necessary to add the `devise` test helpers in the `spec_helper.rb` file:

[source,ruby]
.spec/rails_helper.rb
----
# ...
RSpec.configure do |config|
  # ...
  config.include Devise::Test::ControllerHelpers, :type => :controller
end
----

Now if we run our tests they should be all passing:

[source,bash]
----
$ bundle exec rspec spec/controllers/api/v1/sessions_controller_spec.rb
....

Finished in 0.06515 seconds (files took 0.49218 seconds to load)
4 examples, 0 failures
----

Now this would be a nice moment to commit the changes:

[source,bash]
----
$ git add .
$ git commit -m "Adds sessions controller create action"
----

=== Sign out

We currently have the `sign in` end point for the API. Now it is time to build a `sign out` url. You might wonder why since we are not handling `sessions` and there is nothing to destroy. In this case we are going to update the authentication token so the last one becomes useless and cannot be used again.

NOTE: It is actually not necessary to include this end point, but I do like to include it to expire the authentication tokens.

As usual we start with the tests:

[source,ruby]
.spec/controllers/api/v1/sessions_controller_spec.rb
----
# ...
RSpec.describe Api::V1::SessionsController, type: :controller do
  # ...
  describe "DELETE #destroy" do

    before(:each) do
      @user = FactoryBot.create :user
      sign_in @user, store: false
      delete :destroy, params: { id: @user.auth_token }
    end

    it { expect(response.response_code).to eq(204) }
  end
end
----

As you can see the `test` is super simple. Now we just need to implement the necessary code to make our tests pass:

[source,ruby]
.app/controllers/api/v1/sessions_controller.rb
----
class Api::V1::SessionsController < ApplicationController
  # ...
  def destroy
    user = User.find_by(auth_token: params[:id])
    user.generate_authentication_token!
    user.save
    head 204
  end
end
----

In this case we are expecting an `id` to be sent on the request which has to correspond to the _user authentication token_. We will add the `current_user` method to handle this smoothly. For now we will just leave it like that.

Take a deep breath, we are almost there! In the meantime commit the changes:

[source,bash]
----
$ git add .
$ git commit -m "Adds destroy session action added"
----

== Current User

If you have worked with https://github.com/plataformatec/devise[devise] before you probably are familiar with the auto-generated methods for handling the authentication filters or getting the user that is currently on session. footnote:[See https://github.com/plataformatec/devise#getting-started[documentation] on this for more details).]

In our case we will need to override the `current_user` method to meet our needs, and that is finding the user by the authentication token that is going to be sent on each request to the api. Let me clarify that for you.

Once the client sign ins a user with the correct credentials. The API will return the `authentication token` from that actual user. Each time that client requests for a protected page we will need to fetch the user from that `authentication token` that comes in the request and it could be as a `param` or as a `header`.

In our case we'll be using an `Authorization` header which is commonly used for this type of purpose. I personally find it better because it gives context to the actual request without polluting the URL with extra parameters.

When it comes to authentication I like to add all the related methods into a separate file, and after that just include the file inside the `ApplicationController`. This way it is really easy to test in isolation. Let's create the file under de `controllers/concerns` directory:

[source,bash]
----
$ touch app/controllers/concerns/authenticable.rb
----

After that let's create a `concerns` directory under `spec/controllers/` and an `authenticable_spec.rb` file for our authentication tests.

[source,bash]
----
$ mkdir spec/controllers/concerns
$ touch spec/controllers/concerns/authenticable_spec.rb
----

As usual we start by writing our tests, in this case for our `current_user` method, which will fetch a user by the authentication token ok the `Authorization` header.

[source,ruby]
.spec/controllers/concerns/authenticable_spec.rb
----
# ...
class Authentication < ActionController::API
  include Authenticable
end

RSpec.describe Authenticable do
  let(:authentication) { Authentication.new }
  subject { authentication }

  describe "#current_user" do
    before do
      @user = FactoryBot.create :user
      request.headers["Authorization"] = @user.auth_token
      authentication.stub(:request).and_return(request)
    end
    it "returns the user from the authorization header" do
      expect(authentication.current_user.auth_token).to eql @user.auth_token
    end
  end
end
----

NOTE: If you are wondering: _"Why the hell we created an Authentication class inside the spec file??"_. The answer is simple: when it comes to test modules I find it easy to include them into a temporary class and stub any other methods I may require later.

Our tests should fail. Let's implement the necessary code:

[source,ruby]
.app/controllers/concerns/authenticable.rb
----
module Authenticable
  # Devise methods overwrites
  def current_user
    @current_user ||= User.find_by(auth_token: request.headers['Authorization'])
  end
end
----

Now our tests should be green:

[source]
----
$ rspec spec/controllers/concerns/authenticable_spec.rb
.

Finished in 0.0149 seconds (files took 0.49496 seconds to load)
1 example, 0 failures
----

Now we just need to include the `Authenticable` module into the `ApplicationController`:

[source,ruby]
.app/controllers/application_controller.rb
----
class ApplicationController < ActionController::API
  # ...
  include Authenticable
end
----

This would be a good time to commit the changes:

[source,bash]
----
$ git add .
$ git commit -m "Adds authenticable module for managing authentication methods"
----

== Authenticate with token

Authorization is a big part when building applications because in contrary to authentication that allows us to identify the user in the system, authorization help us to define what they can do.

Although we have a good end point for updating the user it has a major security hole: allowing anyone to update any user on the application. In this section we'll be implementing a method that will require the user to be signed in preventing in this way any unauthorized access. We will return a not authorized JSON message along with its corresponding http code.

First we have to add some tests on the `authenticable_spec.rb` for the `authenticate_with_token` method:

[source,ruby]
.spec/controllers/concerns/authenticable_spec.rb
----
# ...
class Authentication < ActionController::API
  include Authenticable
end

RSpec.describe Authenticable do
  # ...
  describe '#authenticate_with_token' do
    before do
      @user = FactoryBot.create :user
      authentication.stub(:current_user).and_return(nil)
      response.stub(:response_code).and_return(401)
      response.stub(:body).and_return({ 'errors' => 'Not authenticated' }.to_json)
      authentication.stub(:response).and_return(response)
    end

    it 'render a json error message' do
      expect(json_response[:errors]).to eql 'Not authenticated'
    end

    it { expect(response.response_code).to eq(401) }
  end
end
----

As you can see we are using the `Authentication` class again and stubbing the `request` and `response` for handling the expected answer from the server. Now it is time to implement the code to make our tests pass.

[source,ruby]
.app/controllers/concerns/authenticable.rb
----
module Authenticable
  # ...
  def authenticate_with_token!
    unless current_user.present?
      render json: { errors: 'Not authenticated' },
             status: :unauthorized
    end
  end
end
----

At this point we have just built a very simple authorization mechanism to prevent unsigned users from accessing the API. Just update the file `users_controller.rb` with the method `current_user` and prevent access with the command `authenticate_with_token!`!

Let's commit these changes and keep moving forward:

[source,bash]
----
$ git commit -m "Adds the authenticate with token method to handle access to actions"
----

== Authorize actions

It is now time to update our `users_controller.rb` file to deny the access to some of the actions. Also we will implement the `current_user` method on the `update` and `destroy` actions to make sure that the user who is on *`session'* will be capable only to `update` its data or self `destroy`.

We will start with the `update` action. We will no longer fetch the user by id, instead of that by the `auth_token` on the `Authorization` header provided by the current_user method.

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  # ...
  def update
    # we just change method here
    user = current_user

    if user.update(user_params)
      render json: user, status: 200, location: [:api, user]
    else
      render json: { errors: user.errors }, status: 422
    end
  end
  # ...
end
----

And as you might expect, if we run our users controller specs they should fail:

....
$ rspec spec/controllers/api/v1/users_controller_spec.rb
.......FFFFF.

Failures:

  1) Api::V1::UsersController PUT/PATCH #update when is successfully updated renders the json representation for the updated user
     Failure/Error: if user.update(user_params)

     NoMethodError:
       undefined method 'update' for nil:NilClass

   ...
....

The solution is fairly simple: we just need to add the `Authorization` header to the request.

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  # ...
  describe 'PUT/PATCH #update' do
    context 'when is successfully updated' do
      before(:each) do
        @user = FactoryBot.create :user
        request.headers['Authorization'] = @user.auth_token
        patch :update, params: { id: @user.id, user: { email: 'newmail@example.com' } }, format: :json
      end
      # ...
    end

    context 'when is not created' do
      before(:each) do
        @user = FactoryBot.create :user
        request.headers['Authorization'] = @user.auth_token
        patch :update, params: { id: @user.id, user: { email: 'bademail.com' } }, format: :json
      end
      # ...
    end
  end
  # ...
end
----

Now the tests should be all green. But wait something does not feel quite right isn't it? We can refactor the line we just added and put it on the `HeadersHelpers` module we build:

[source,ruby]
.spec/support/request_helpers.rb
----
module Request
  # ...
  module HeadersHelpers
    # ...
    def api_authorization_header(token)
      request.headers['Authorization'] = token
    end
  end
end
----

Now each time we need to have the `current_user` on our specs we simply call the `api_authorization_header` method. I'll let you do that with the `users_controller_spec.rb` for the update spec. For the destroy action we will do the same, because we just have to make sure a user is capable to self destroy

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  # ...
  describe 'PUT/PATCH #update' do
    context 'when is successfully updated' do
      before(:each) do
        @user = FactoryBot.create :user
        api_authorization_header @user.auth_token
        patch :update, params: { id: @user.id, user: { email: 'newmail@example.com' } }, format: :json
      end
      # ...
    end

    context 'when is not created' do
      before(:each) do
        @user = FactoryBot.create :user
        api_authorization_header @user.auth_token
        patch :update, params: { id: @user.id, user: { email: 'bademail.com' } }, format: :json
      end
      # ...
    end
  end
  # ...
end
----

Now for the spec file and as mentioned before, we just need to add the `api_authorization_header`:

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  # ...
  def destroy
    current_user.destroy
    head 204
  end
  # ...
end
----

Now for the spec file and as mentioned before, we just need to add the `api_authorization_header`:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  # ...
  describe 'DELETE #destroy' do
    before(:each) do
      @user = FactoryBot.create :user
      api_authorization_header @user.auth_token
      delete :destroy, params: { id: @user.id }
    end

    it { expect(response.response_code).to eq(204) }
  end
end
----

We should have all of our tests passing. The last step for this section consist on adding the corresponding authorization access for these last two actions.

NOTE: It is common to just prevent the actions on which the user is performing actions on the record itself (in this case the `destroy` and `update` action).

On the `users_controller.rb` we have to filter some these actions to prevent the access

[source,ruby]
.app/controllers/api/v1/users_controller.rb
----
class Api::V1::UsersController < ApplicationController
  before_action :authenticate_with_token!, only: %i[update destroy]
  respond_to :json
  # ...
end
----

Our tests should still be passing. And from now on every time we want to prevent any action from being trigger we simply add the `authenticate_with_token!` method on a `before_action` hook.

Let's just commit this:

[source,bash]
----
$ git add .
$ git commit -m "Adds authorization for the users controller"
----

Lastly but not least we will finish the chapter by refactoring the `authenticate_with_token!` method. It is really a small enhancement but it will make the method more descriptive. You'll see what I mean in a minute. But first things first let's add some specs.

[source,ruby]
.spec/controllers/concerns/authenticable_spec.rb
----
# ...
RSpec.describe Authenticable do
  # ...
  describe '#user_signed_in?' do
    context "when there is a user on 'session'" do
      before do
        @user = FactoryBot.create :user
        authentication.stub(:current_user).and_return(@user)
      end

      it { should be_user_signed_in }
    end

    context "when there is no user on 'session'" do
      before do
        @user = FactoryBot.create :user
        authentication.stub(:current_user).and_return(nil)
      end

      it { should_not be_user_signed_in }
    end
  end
end
----

As you can see we added two simple specs to know whether the user is signed in or not (As I mentioned early it is just for visual clarity). But let's keep going and add the implementation.

[source,ruby]
.app/controllers/concerns/authenticable.rb
----
module Authenticable
  # ...
  def authenticate_with_token!
    unless user_signed_in?
      render json: { errors: 'Not authenticated' },
             status: :unauthorized
    end
  end

  def user_signed_in?
    current_user.present?
  end
end
----

As you can see, now the `authenticate_with_token!` it's easier to read not just for you but for other developers joining the project. This approach has also another side benefit. In any case you want to change or extend how to validate if the user is signed in you can just do it on the `user_signed_in?` method.

Now our tests should be all green:

[source,bash]
----
$ rspec spec/controllers/concerns/authenticable_spec.rb
.....

Finished in 0.07415 seconds (files took 0.702 seconds to load)
5 examples, 0 failures
----

Let's commit the changes:

[source,bash]
----
$ git add .
$ git commit -m "Adds user_signed_in? method to know whether the user is logged in or not"
----

== Conclusion

Yeah! you made it! you are half way done! Keep up the good work. This chapter was a long and hard one but it is a great step forward on setting a solid mechanism for handling user authentication. We even scratch the surface for simple authorization rules.

In the next chapter we will be focusing on customizing the JSON output for the user with `active_model_serializers` gem and adding a `product` model to the equation by giving the user the ability to create a product and publish it for sale.
