[#chapter04-refactoring-tests]
= Refactoring tests

In previous chapter we manage to put together some `user` resources endpoints. If you skip it (or simple missed it) I highly recommend you take a look at it. It covers the first test specs and an introduction to JSON responses.

You can clone the project until this point with:

[source,bash]
----
$ git clone --branch chapitre_3 https://github.com/madeindjs/market_place_api
----

In this chapter we’ll refactor our test specs by adding some helper methods. We'll also remove the `format` param sent on every request and do it through headers. Also we hopefully build more consistent and scalable test suite.

So let’ take a look to the `users_controller_spec.rb` file:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
RSpec.describe Api::V1::UsersController, type: :controller do
  before(:each) { request.headers['Accept'] = 'application/vnd.marketplace.v1' }

  describe 'GET #show' do
    before(:each) do
      @user = FactoryBot.create :user
      get :show, params: { id: @user.id, format: :json }
    end

    it 'returns the information about a reporter on a hash' do
      user_response = JSON.parse(response.body, symbolize_names: true)
      expect(user_response[:email]).to eql @user.email
    end

    it { expect(response.response_code).to eq(200) }
  end

  describe 'POST #create' do
    context 'when is successfully created' do
      before(:each) do
        @user_attributes = FactoryBot.attributes_for :user
        post :create, params: { user: @user_attributes }, format: :json
      end

      it 'renders the json representation for the user record just created' do
        user_response = JSON.parse(response.body, symbolize_names: true)
        expect(user_response[:email]).to eql @user_attributes[:email]
      end

      it { expect(response.response_code).to eq(201) }
    end

    context 'when is not created' do
      before(:each) do
        # notice I'm not including the email
        @invalid_user_attributes = { password: '12345678',
                                     password_confirmation: '12345678' }
        post :create, params: { user: @invalid_user_attributes }, format: :json
      end

      it 'renders an errors json' do
        user_response = JSON.parse(response.body, symbolize_names: true)
        expect(user_response).to have_key(:errors)
      end

      it 'renders the json errors on why the user could not be created' do
        user_response = JSON.parse(response.body, symbolize_names: true)
        expect(user_response[:errors][:email]).to include "can't be blank"
      end

      it {  expect(response.response_code).to eq(422) }
    end
  end

  describe "PUT/PATCH #update" do

   context "when is successfully updated" do
     before(:each) do
       @user = FactoryBot.create :user
       patch :update, params: {
         id: @user.id,
         user: { email: "newmail@example.com" } },
         format: :json
     end

     it "renders the json representation for the updated user" do
       user_response = JSON.parse(response.body, symbolize_names: true)
       expect(user_response[:email]).to eql "newmail@example.com"
     end

     it {  expect(response.response_code).to eq(200) }
   end

   context "when is not created" do
     before(:each) do
       @user = FactoryBot.create :user
       patch :update, params: {
         id: @user.id,
         user: { email: "bademail.com" } },
         format: :json
     end

     it "renders an errors json" do
       user_response = JSON.parse(response.body, symbolize_names: true)
       expect(user_response).to have_key(:errors)
     end

     it "renders the json errors on why the user could not be created" do
       user_response = JSON.parse(response.body, symbolize_names: true)
       expect(user_response[:errors][:email]).to include "is invalid"
     end

     it {  expect(response.response_code).to eq(422) }
   end
  end

  describe "DELETE #destroy" do
    before(:each) do
      @user = FactoryBot.create :user
      delete :destroy, params: { id: @user.id }, format: :json
    end

    it { expect(response.response_code).to eq(204) }
  end
end
----

As you can see there is a lot of duplicated code, two big refactors here are:

* The `JSON.parse` method can be encapsulated on a method.
* The `format` param is sent on every request. Although is not a bad practice but it is better if you handle the response type through headers.

So let’s add a method for handling the JSON response. If you have been following the tutorial you may know that we are creating a branch for each chapter. So let’s do that:

[source,bash]
----
$ git checkout -b chapter4
----

== Refactoring the JSON response

Back to the `refactor`, we will add file under the `spec/support` directory. Currently we don’t have this directory. So let’s add it:

[source,bash]
----
$ mkdir spec/support
----

Then we create a `request_helpers.rb` file under the just created `support` directory:

[source,bash]
----
$ touch spec/support/request_helpers.rb
----

It is time to extract the `JSON.parse` method into our own support method:

[source,ruby]
.spec/support/request_helpers.rb
----
module Request
  module JsonHelpers
    def json_response
      @json_response ||= JSON.parse(response.body, symbolize_names: true)
    end
  end
end
----

We scope the method into some `modules` just to keep our code nice and organized. The next step here is to update the `users_controller_spec.rb` file to use the method. A quick example is presented below:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
# ...
it 'returns the information about a reporter on a hash' do
  user_response = json_response # c'est cette ligne qui est maj
  expect(user_response[:email]).to eql @user.email
end
# ...
----

Now it is your turn to update the whole file.

After you are done updating the file and if you tried to run your tests you probably encounter a problem. For some reason it is not finding the `json_response` method which is weird because if we take a look at the `spec_helper.rb` file. We can see that is actually loading all files from the `support` directory:

[source,ruby]
.spec/rails_helper.rb
----
# Load all Ruby files placed in spec/support folder
Dir[Rails.root.join('spec', 'support', '**', '*.rb')].each do |f|
  require f
end

RSpec.configure do |config|
  #  ...
  # We also need to include JsonHelpers methods in Rspec tests
  config.include Request::JsonHelpers, :type => :controller
  #  ...
end
----

After that if we run our tests again, everything should be green again. So let’s commit this before adding more code:

[source,bash]
----
$ git add .
$ git commit -m "Refactors the json parse method"
----

== Refactoring the format param

We want to remove the `format` param sent on every request and instead of that let’s handle the response we are expecting through headers. This is extremely easy just by adding one line to our `users_controller_spec.rb` file:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
RSpec.describe Api::V1::UsersController, type: :controller do
  before(:each) { request.headers['Accept'] = "application/vnd.marketplace.v1, application/json" }
----

By adding this line, you can now remove all the `format` param we were sending on each request and forget about it for the whole application, as long as you include the `Accept` header with the JSON mime type.

Wait we are not over yet! We can add another header to our request that will help us describe the data contained we are expecting from the server to deliver. We can achieve this fairly easy by adding one more line specifying the `Content-Type` header:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
RSpec.describe Api::V1::UsersController, type: :controller do
  before(:each) { request.headers['Accept'] = "application/vnd.marketplace.v1, application/json" }
  before(:each) { request.headers['Content-Type'] = 'application/json' }
----

And again if we run our tests we can see they are all nice and green:

[source,bash]
----
$ bundle exec rspec spec/controllers/api/v1/users_controller_spec.rb
.............

Finished in 1.44 seconds (files took 0.4734 seconds to load)
13 examples, 0 failures
----

As always this is a good time to commit:

[source,bash]
----
$ git commit -am "Factorize format for unit tests"
----

== Refactor before actions

I’m very happy with the code we got so far but we can still improve it a little bit. The first thing that comes to my mind is to group the three custom headers being added before each request:

[source,ruby]
.spec/controllers/api/v1/users_controller_spec.rb
----
#...
before(:each) { request.headers['Accept'] = "application/vnd.marketplace.v1, application/json" }
before(:each) { request.headers['Content-Type'] = 'application/json' }
----

This is good but not good enough because we will have to add this five lines of code for each file. If for some reason we are changing this (let’s say the response type to `xml`) well you do the math. But don’t worry I provide you a solution which will solve all these problems.

First of all we have to extend our `request_helpers.rb` file to include another module, which I named `HeadersHelpers` and which will have the necessary methods to handle these custom headers

[source,ruby]
.spec/support/request_helpers.rb
----
module Request
  # ...
  module HeadersHelpers
    def api_header(version = 1)
      request.headers['Accept'] = "application/vnd.marketplace.v#{version}"
    end

    def api_response_format(format ='application/json')
      request.headers['Accept'] = "#{request.headers['Accept']}, #{format}"
      request.headers['Content-Type'] = format
    end

    def include_default_accept_headers
      api_header
      api_response_format
    end
  end
end
----

As you can see I broke the calls into two methods: one for setting the API header and the other one for setting the response format. Also and for convenience I wrote a method `include_default_accept_headers` for calling those two.

And now to call this method before each of our test cases we can add the `before` hook footnote:[An hook allow you to run a specific method when a method is called] on the _Rspec.configure_ block at `spec_helper.rb` file, and make sure we specify the type to `:controller`, as we don’t to run this on unit tests.

[source,ruby]
.spec/rails_helper.rb
----
# ...
RSpec.configure do |config|
  # ...
  config.include Request::HeadersHelpers, :type => :controller
  config.before(:each, type: :controller) do
    include_default_accept_headers
  end
  # ...
end
----

After adding this lines we can remove the before hooks on the `users_controller_spec.rb` file and check that our tests are still passing. You can review a full version of the `spec_helper.rb` file below:

[source,ruby]
.spec/rails_helper.rb
----
require 'spec_helper'
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
# Prevent database truncation if the environment is production
abort("The Rails environment is running in production mode!") if Rails.env.production?
require 'rspec/rails'

Dir[Rails.root.join('spec', 'support', '**', '*.rb')].each { |f| require f }

begin
  ActiveRecord::Migration.maintain_test_schema!
rescue ActiveRecord::PendingMigrationError => e
  puts e.to_s.strip
  exit 1
end

RSpec.configure do |config|
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = true

  config.include Devise::Test::ControllerHelpers, type: :controller
  config.include Request::JsonHelpers, :type => :controller
  config.include Request::HeadersHelpers, :type => :controller
  config.before(:each, type: :controller) do
    include_default_accept_headers
  end

  config.infer_spec_type_from_file_location!
  config.filter_rails_from_backtrace!
end
----

Well now I do feel satisfied with the code, let’s commit the changes:

[source,bash]
----
$ git commit -am "Refactors test headers for each request"
----

Remember you can review the code up to this point at the https://github.com/madeindjs/api_on_rails[GitHub repository].

== Conclusion

Nice job on finishing this chapter. Although it was a short one it was a crucial step as this will help us write better and faster tests. On next chapter we will add the authentication mechanism so we’ll be using across the application as well as limiting the access for certain actions.
